defmodule Supportdesk.Repo.Migrations.AddForeignKeyIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:audit_events, [:org, :ticket_id])

    create index(:comments, [:org, :ticket_id])

    create index(:ticket_tags, [:org, :ticket_id])

    create index(:tickets, [:org, :assignee_id])
  end

  def down do
    drop_if_exists(index(:tickets, [:org, :assignee_id]))

    drop_if_exists(index(:ticket_tags, [:org, :ticket_id]))

    drop_if_exists(index(:comments, [:org, :ticket_id]))

    drop_if_exists(index(:audit_events, [:org, :ticket_id]))
  end
end
