defmodule Supportdesk.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org, :text, null: false)
      add(:name, :text, null: false)
      add(:email, :text, null: false)
      add(:role, :text, null: false)
      add(:active, :boolean, null: false, default: true)
    end

    create unique_index(:agents, [:org, :email], name: "agents_unique_email_index")

    create table(:audit_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org, :text, null: false)
      add(:ticket_id, :uuid, null: false)
      add(:actor_id, :uuid)
      add(:kind, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:comments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org, :text, null: false)

      add(
        :author_id,
        references(:agents,
          column: :id,
          name: "comments_author_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:body, :text, null: false)
      add(:internal, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:ticket_id, :uuid, null: false)
    end

    create table(:orgs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:slug, :text, null: false)
    end

    create unique_index(:orgs, [:slug], name: "orgs_unique_slug_index")

    create table(:tags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org, :text, null: false)
      add(:name, :text, null: false)
    end

    create unique_index(:tags, [:org, :name], name: "tags_unique_name_index")

    create table(:ticket_tags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org, :text, null: false)
      add(:ticket_id, :uuid, null: false)
      add(:tag_id, :uuid, null: false)
    end

    create table(:tickets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:comments) do
      modify(
        :ticket_id,
        references(:tickets,
          column: :id,
          name: "comments_ticket_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:tickets) do
      add(:org, :text, null: false)
      add(:subject, :text, null: false)
      add(:body, :text, null: false)
      add(:priority, :bigint, null: false)
      add(:confidential, :boolean, null: false, default: false)
      add(:requester_email, :text)
      add(:status, :text, null: false, default: "new")
      add(:view_count, :bigint, null: false, default: 0)
      add(:reopen_count, :bigint, null: false, default: 0)
      add(:version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :assignee_id,
        references(:agents,
          column: :id,
          name: "tickets_assignee_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :author_id,
        references(:agents,
          column: :id,
          name: "tickets_author_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:tickets, "tickets_author_id_fkey"))

    drop(constraint(:tickets, "tickets_assignee_id_fkey"))

    alter table(:tickets) do
      remove(:author_id)
      remove(:assignee_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:version)
      remove(:reopen_count)
      remove(:view_count)
      remove(:status)
      remove(:requester_email)
      remove(:confidential)
      remove(:priority)
      remove(:body)
      remove(:subject)
      remove(:org)
    end

    drop(constraint(:comments, "comments_ticket_id_fkey"))

    drop(constraint(:comments, "comments_author_id_fkey"))

    alter table(:comments) do
      modify(:ticket_id, :uuid)
    end

    drop(table(:tickets))

    drop(table(:ticket_tags))

    drop_if_exists(unique_index(:tags, [:org, :name], name: "tags_unique_name_index"))

    drop(table(:tags))

    drop_if_exists(unique_index(:orgs, [:slug], name: "orgs_unique_slug_index"))

    drop(table(:orgs))

    drop(table(:comments))

    drop(table(:audit_events))

    drop_if_exists(unique_index(:agents, [:org, :email], name: "agents_unique_email_index"))

    drop(table(:agents))
  end
end
