{application,sasl,
             [{description,"SASL  CXC 138 11"},
              {vsn,"4.4"},
              {modules,[sasl,alarm_handler,format_lib_supp,misc_supp,rb,
                        rb_format_supp,release_handler,release_handler_1,
                        erlsrv,sasl_report,sasl_report_tty_h,
                        sasl_report_file_h,systools,systools_make,systools_rc,
                        systools_relup,systools_lib]},
              {registered,[sasl_sup,alarm_handler,release_handler]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {mod,{sasl,[]}},
              {runtime_dependencies,["tools-2.6.14","stdlib-4.0","kernel-6.0",
                                     "erts-15.0"]}]}.
