//! TypeScript and Zod code generator orchestrator.

use ash_core::{DomainDef, ResourceDef};
use thiserror::Error;

use crate::client::{
    generate_domain_client, generate_resource_client, generate_resource_query_builder,
    generate_root_client, generate_selection_set_builder, generate_transport_runtime,
};
use crate::config::TypeScriptConfig;
use crate::react::generate_resource_react_hooks;
use crate::types::{generate_common_types, generate_resource_types};
use crate::zod::generate_resource_zod;

/// Error type for TypeScript generator.
#[derive(Debug, Error)]
pub enum CodegenError {
    #[error("No resources or domains provided for TypeScript generation")]
    EmptyInput,
}

/// Consolidated or modular output files generated from Ash resources.
#[derive(Clone, Debug)]
pub struct GeneratedBundle {
    pub types_ts: String,
    pub zod_ts: Option<String>,
    pub client_ts: Option<String>,
    pub index_ts: String,
}

/// The top-level TypeScript generator for Ash domains and resources.
#[derive(Clone, Debug, Default)]
pub struct TypeScriptGenerator {
    config: TypeScriptConfig,
    resources: Vec<&'static ResourceDef>,
    domains: Vec<&'static DomainDef>,
}

impl TypeScriptGenerator {
    /// Create a new generator with default configuration.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the configuration.
    pub fn config(mut self, config: TypeScriptConfig) -> Self {
        self.config = config;
        self
    }

    /// Add a resource to be generated.
    pub fn add_resource(mut self, res: &'static ResourceDef) -> Self {
        if !self.resources.iter().any(|r| r.name == res.name) {
            self.resources.push(res);
        }
        self
    }

    /// Add multiple resources.
    pub fn add_resources(mut self, resources: &[&'static ResourceDef]) -> Self {
        for res in resources {
            self = self.add_resource(res);
        }
        self
    }

    /// Add a domain to be generated (also automatically includes all its resources).
    pub fn add_domain(mut self, domain: &'static DomainDef) -> Self {
        if !self.domains.iter().any(|d| d.name == domain.name) {
            self.domains.push(domain);
        }
        for res in domain.resources {
            self = self.add_resource(res);
        }
        self
    }

    /// Generate a single consolidated TypeScript file containing types, Zod schemas, client SDK, and hooks.
    pub fn generate_consolidated(&self) -> Result<String, CodegenError> {
        if self.resources.is_empty() && self.domains.is_empty() {
            return Err(CodegenError::EmptyInput);
        }

        let mut out = String::new();

        out.push_str("// ========================================================\n");
        out.push_str("// Automatically generated by ash-typescript. DO NOT EDIT.\n");
        out.push_str("// ========================================================\n\n");

        if self.config.generate_zod {
            out.push_str("import { z } from \"zod\";\n\n");
        }

        // 1. Common types (PageInfo, SortOrder, Filters)
        out.push_str("// --- Section 1: Common Types & Filters ---\n");
        out.push_str(&generate_common_types());
        out.push('\n');

        // 2. Resource types (Interfaces, Action Inputs, Filter/Sort/Include)
        out.push_str("// --- Section 2: Resource Types & Action Inputs ---\n");
        for res in &self.resources {
            out.push_str(&generate_resource_types(res));
            out.push('\n');
        }

        // 3. Zod Schemas
        if self.config.generate_zod {
            out.push_str("// --- Section 3: Zod Validation Schemas ---\n");
            for res in &self.resources {
                out.push_str(&generate_resource_zod(res));
                out.push('\n');
            }
        }

        // 4. Client SDK & Transport
        if self.config.generate_client {
            out.push_str("// --- Section 4: Isomorphic Client SDK & Transport ---\n");
            out.push_str(&generate_transport_runtime(&self.config.graphql_endpoint));
            out.push('\n');

            // Selection set builders
            for res in &self.resources {
                out.push_str(&generate_selection_set_builder(res));
            }

            // Query builders
            for res in &self.resources {
                out.push_str(&generate_resource_query_builder(res));
            }

            // Resource clients
            for res in &self.resources {
                out.push_str(&generate_resource_client(res));
            }

            // Domain clients
            for domain in &self.domains {
                out.push_str(&generate_domain_client(domain));
            }

            // Root client
            out.push_str(&generate_root_client(
                &self.config.client_class_name,
                &self.resources,
                &self.domains,
            ));
            out.push('\n');
        }

        // 5. React Hooks helpers
        if self.config.generate_react && self.config.generate_client {
            out.push_str("// --- Section 5: React & TanStack Query Helpers ---\n");
            for res in &self.resources {
                out.push_str(&generate_resource_react_hooks(res, &self.config.client_class_name));
            }
        }

        Ok(out)
    }

    /// Generate a modular bundle of separate files (types.ts, zod.ts, client.ts, index.ts).
    pub fn generate_bundle(&self) -> Result<GeneratedBundle, CodegenError> {
        if self.resources.is_empty() && self.domains.is_empty() {
            return Err(CodegenError::EmptyInput);
        }

        // Types file
        let mut types_ts = String::new();
        types_ts.push_str("// Automatically generated by ash-typescript.\n\n");
        types_ts.push_str(&generate_common_types());
        types_ts.push('\n');
        for res in &self.resources {
            types_ts.push_str(&generate_resource_types(res));
            types_ts.push('\n');
        }

        // Zod file
        let zod_ts = if self.config.generate_zod {
            let mut z = String::new();
            z.push_str("// Automatically generated by ash-typescript.\n");
            z.push_str("import { z } from \"zod\";\n\n");
            for res in &self.resources {
                z.push_str(&generate_resource_zod(res));
                z.push('\n');
            }
            Some(z)
        } else {
            None
        };

        // Client file
        let client_ts = if self.config.generate_client {
            let mut c = String::new();
            c.push_str("// Automatically generated by ash-typescript.\n");
            c.push_str("import type {\n");
            c.push_str("  PageInfo, PaginatedResult, SortOrder,\n");
            for res in &self.resources {
                c.push_str(&format!(
                    "  {}, {}Include, {}FilterInput, {}SortInput, {}SortField,\n",
                    res.name, res.name, res.name, res.name, res.name
                ));
            }
            c.push_str("} from \"./types\";\n\n");

            c.push_str(&generate_transport_runtime(&self.config.graphql_endpoint));
            c.push('\n');

            for res in &self.resources {
                c.push_str(&generate_selection_set_builder(res));
            }
            for res in &self.resources {
                c.push_str(&generate_resource_query_builder(res));
            }
            for res in &self.resources {
                c.push_str(&generate_resource_client(res));
            }
            for domain in &self.domains {
                c.push_str(&generate_domain_client(domain));
            }
            c.push_str(&generate_root_client(
                &self.config.client_class_name,
                &self.resources,
                &self.domains,
            ));

            if self.config.generate_react {
                for res in &self.resources {
                    c.push_str(&generate_resource_react_hooks(res, &self.config.client_class_name));
                }
            }

            Some(c)
        } else {
            None
        };

        // Index file re-exporting everything
        let mut index_ts = String::new();
        index_ts.push_str("// Automatically generated by ash-typescript.\n");
        index_ts.push_str("export * from \"./types\";\n");
        if self.config.generate_zod {
            index_ts.push_str("export * from \"./zod\";\n");
        }
        if self.config.generate_client {
            index_ts.push_str("export * from \"./client\";\n");
        }

        Ok(GeneratedBundle {
            types_ts,
            zod_ts,
            client_ts,
            index_ts,
        })
    }
}
