//! Code generation from `ash-sql` table snapshots.

use std::collections::HashMap;
use ash_sql::TableSnapshot;

use crate::config::TypeScriptConfig;
use crate::generator::CodegenError;
use crate::types::{generate_common_types, to_camel_case, to_pascal_case};

/// Deduce a singular PascalCase resource name from a database table name.
pub fn table_to_resource_name(table: &str) -> String {
    let singular = if let Some(stripped) = table.strip_suffix("ies") {
        format!("{stripped}y")
    } else if let Some(stripped) = table.strip_suffix("sses") {
        format!("{stripped}ss")
    } else if let Some(stripped) = table.strip_suffix('s') {
        if stripped.ends_with('s') {
            table.to_string()
        } else {
            stripped.to_string()
        }
    } else {
        table.to_string()
    };
    to_pascal_case(&singular)
}

/// Map a SQL column type to TypeScript type, Filter type, and Zod validator.
pub fn sql_type_to_ts_and_zod(sql_type: &str, nullable: bool) -> (&'static str, &'static str, String) {
    let upper = sql_type.to_ascii_uppercase();
    let (ts_type, filter_type, base_zod) = if upper.contains("UUID") {
        ("string", "UuidFilter", "z.string().uuid()")
    } else if upper.contains("INT") || upper.contains("SERIAL") {
        ("number", "IntFilter", "z.number().int()")
    } else if upper.contains("BOOL") {
        ("boolean", "BooleanFilter", "z.boolean()")
    } else if upper.contains("FLOAT") || upper.contains("DOUBLE") || upper.contains("REAL") {
        ("number", "FloatFilter", "z.number()")
    } else if upper.contains("NUMERIC") || upper.contains("DECIMAL") {
        ("number", "IntFilter", "z.number()")
    } else if upper.contains("BYTEA") || upper.contains("BLOB") {
        ("string", "StringFilter", "z.string()")
    } else if upper.contains("JSON") {
        ("Record<string, unknown>", "JsonFilter", "z.record(z.string(), z.unknown())")
    } else {
        ("string", "StringFilter", "z.string()")
    };

    let zod_str = if nullable {
        format!("{base_zod}.nullable().optional()")
    } else {
        base_zod.to_string()
    };

    (ts_type, filter_type, zod_str)
}

/// Generate consolidated TypeScript SDK from a slice of TableSnapshots.
pub fn generate_from_snapshots(
    snapshots: &[TableSnapshot],
    config: &TypeScriptConfig,
) -> Result<String, CodegenError> {
    if snapshots.is_empty() {
        return Err(CodegenError::EmptyInput);
    }

    let mut out = String::new();
    out.push_str("// ========================================================\n");
    out.push_str("// Automatically generated by cargo ash codegen ts. DO NOT EDIT.\n");
    out.push_str("// ========================================================\n\n");

    if config.generate_zod {
        out.push_str("import { z } from \"zod\";\n\n");
    }

    // 1. Common Types
    out.push_str("// --- Section 1: Common Types & Filters ---\n");
    out.push_str(&generate_common_types());
    out.push('\n');

    // Table to Resource Name map
    let mut table_to_res: HashMap<&str, String> = HashMap::new();
    for s in snapshots {
        table_to_res.insert(&s.table, table_to_resource_name(&s.table));
    }

    // 2. Resource Types
    out.push_str("// --- Section 2: Resource Types & Inputs ---\n");
    for s in snapshots {
        let name = &table_to_res[s.table.as_str()];

        // Model Interface
        out.push_str(&format!("export interface {name} {{\n"));
        for col in &s.columns {
            let (ts_type, _, _) = sql_type_to_ts_and_zod(&col.sql_type, col.nullable);
            if col.nullable {
                out.push_str(&format!("  {}?: {} | null;\n", col.name, ts_type));
            } else {
                out.push_str(&format!("  {}: {};\n", col.name, ts_type));
            }
        }
        for r in &s.references {
            if let Some(target_res) = table_to_res.get(r.target_table.as_str()) {
                let rel_name = r.column.strip_suffix("_id").unwrap_or(&r.column);
                out.push_str(&format!("  {}?: {} | null;\n", rel_name, target_res));
            }
        }
        out.push_str("}\n\n");

        // Input Interface (Create/Update)
        out.push_str(&format!("export interface {name}Input {{\n"));
        for col in &s.columns {
            if col.is_primary_key {
                continue;
            }
            let (ts_type, _, _) = sql_type_to_ts_and_zod(&col.sql_type, col.nullable);
            if col.nullable {
                out.push_str(&format!("  {}?: {} | null;\n", col.name, ts_type));
            } else {
                out.push_str(&format!("  {}: {};\n", col.name, ts_type));
            }
        }
        out.push_str("}\n\n");

        // Filter Input
        out.push_str(&format!("export interface {name}FilterInput {{\n"));
        for col in &s.columns {
            let (_, filter_type, _) = sql_type_to_ts_and_zod(&col.sql_type, col.nullable);
            out.push_str(&format!("  {}?: {};\n", col.name, filter_type));
        }
        out.push_str(&format!("  and?: {name}FilterInput[];\n"));
        out.push_str(&format!("  or?: {name}FilterInput[];\n"));
        out.push_str(&format!("  not?: {name}FilterInput;\n"));
        out.push_str("}\n\n");

        // Sort Input
        let sort_fields = s
            .columns
            .iter()
            .map(|c| format!("\"{}\"", c.name))
            .collect::<Vec<_>>()
            .join(" | ");
        out.push_str(&format!("export type {name}SortField = {sort_fields};\n\n"));
        out.push_str(&format!("export interface {name}SortInput {{\n"));
        out.push_str(&format!("  field: {name}SortField;\n"));
        out.push_str("  order?: SortOrder;\n");
        out.push_str("}\n\n");

        // Include Input
        out.push_str(&format!("export interface {name}Include {{\n"));
        for r in &s.references {
            if let Some(target_res) = table_to_res.get(r.target_table.as_str()) {
                let rel_name = r.column.strip_suffix("_id").unwrap_or(&r.column);
                out.push_str(&format!("  {}?: boolean | {target_res}Include;\n", rel_name));
            }
        }
        out.push_str("}\n\n");
    }

    // 3. Zod Schemas
    if config.generate_zod {
        out.push_str("// --- Section 3: Zod Validation Schemas ---\n");
        for s in snapshots {
            let name = &table_to_res[s.table.as_str()];
            out.push_str(&format!("export const {name}Schema = z.object({{\n"));
            for col in &s.columns {
                let (_, _, zod_str) = sql_type_to_ts_and_zod(&col.sql_type, col.nullable);
                out.push_str(&format!("  {}: {},\n", col.name, zod_str));
            }
            out.push_str("});\n\n");

            out.push_str(&format!("export const {name}InputSchema = z.object({{\n"));
            for col in &s.columns {
                if col.is_primary_key {
                    continue;
                }
                let (_, _, zod_str) = sql_type_to_ts_and_zod(&col.sql_type, col.nullable);
                out.push_str(&format!("  {}: {},\n", col.name, zod_str));
            }
            out.push_str("});\n\n");
        }
    }

    // 4. Client SDK & Selection Set Builders
    if config.generate_client {
        out.push_str("// --- Section 4: Isomorphic Client SDK ---\n");
        out.push_str(&crate::client::generate_transport_runtime(&config.graphql_endpoint));
        out.push('\n');

        for s in snapshots {
            let name = &table_to_res[s.table.as_str()];
            let base_attrs = s
                .columns
                .iter()
                .map(|c| c.name.as_str())
                .collect::<Vec<_>>()
                .join(" ");

            out.push_str(&format!("export function build{name}SelectionSet(include?: {name}Include): string {{\n"));
            out.push_str(&format!("  let fields = \"{base_attrs}\";\n"));
            for r in &s.references {
                if let Some(target_res) = table_to_res.get(r.target_table.as_str()) {
                    let rel_name = r.column.strip_suffix("_id").unwrap_or(&r.column);
                    out.push_str(&format!("  if (include?.{rel_name}) {{\n"));
                    out.push_str(&format!("    const subInclude = typeof include.{rel_name} === \"object\" ? include.{rel_name} : undefined;\n"));
                    out.push_str(&format!("    fields += ` {rel_name} {{ ${{build{target_res}SelectionSet(subInclude)}} }}`;\n"));
                    out.push_str("  }\n");
                }
            }
            out.push_str("  return fields;\n");
            out.push_str("}\n\n");

            // Query Builder
            let list_q = crate::client::list_query_name(name);
            let conn_q = crate::client::connection_query_name(name);
            out.push_str(&format!(
                r#"export class {name}QueryBuilder {{
  private _filter?: {name}FilterInput;
  private _sort: {name}SortInput[] = [];
  private _limit?: number;
  private _offset?: number;
  private _include?: {name}Include;

  constructor(private readonly transport: AshTransport) {{}}

  public filter(filter?: {name}FilterInput): this {{
    this._filter = filter;
    return this;
  }}

  public sort(field: {name}SortField, order: SortOrder = "asc"): this {{
    this._sort.push({{ field, order }});
    return this;
  }}

  public limit(limit: number): this {{
    this._limit = limit;
    return this;
  }}

  public offset(offset: number): this {{
    this._offset = offset;
    return this;
  }}

  public include(include: {name}Include): this {{
    this._include = {{ ...this._include, ...include }};
    return this;
  }}

  public async all(): Promise<{name}[]> {{
    const fields = build{name}SelectionSet(this._include);
    const query = `query List{name}($filter: {name}FilterInput, $sort: [{name}SortInput!], $limit: Int, $offset: Int) {{
      {list_q}(filter: $filter, sort: $sort, limit: $limit, offset: $offset) {{
        ${{fields}}
      }}
    }}`;

    const data = await this.transport.request<{{ {list_q}: {name}[] }}>(query, {{
      filter: this._filter,
      sort: this._sort.length > 0 ? this._sort : undefined,
      limit: this._limit,
      offset: this._offset,
    }});

    return data.{list_q};
  }}

  public async first(): Promise<{name} | null> {{
    this._limit = 1;
    const list = await this.all();
    return list[0] ?? null;
  }}

  public async page(first: number = 20, after?: string): Promise<PaginatedResult<{name}>> {{
    const fields = build{name}SelectionSet(this._include);
    const query = `query Conn{name}($filter: {name}FilterInput, $sort: [{name}SortInput!], $first: Int, $after: String) {{
      {conn_q}(filter: $filter, sort: $sort, first: $first, after: $after) {{
        edges {{
          node {{
            ${{fields}}
          }}
          cursor
        }}
        pageInfo {{
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }}
        totalCount
      }}
    }}`;

    const data = await this.transport.request<{{
      {conn_q}: {{
        edges: Array<{{ node: {name}; cursor: string }}>;
        pageInfo: PageInfo;
        totalCount?: number;
      }};
    }}>(query, {{
      filter: this._filter,
      sort: this._sort.length > 0 ? this._sort : undefined,
      first,
      after,
    }});

    const conn = data.{conn_q};
    return {{
      results: conn.edges.map((e) => e.node),
      pageInfo: conn.pageInfo,
      totalCount: conn.totalCount,
    }};
  }}

  public queryOptions() {{
    return {{
      queryKey: [
        "{name}",
        "query",
        {{
          filter: this._filter,
          sort: this._sort,
          limit: this._limit,
          offset: this._offset,
          include: this._include,
        }},
      ],
      queryFn: () => this.all(),
    }};
  }}
}}

"#
            ));

            // Client class
            let get_q = crate::client::get_query_name(name);
            let create_m = format!("create{}", name);
            let update_m = format!("update{}", name);
            let destroy_m = format!("destroy{}", name);
            out.push_str(&format!(
                r#"export class {name}Client {{
  constructor(private readonly transport: AshTransport) {{}}

  public query(): {name}QueryBuilder {{
    return new {name}QueryBuilder(this.transport);
  }}

  public async get(id: string, include?: {name}Include): Promise<{name} | null> {{
    const fields = build{name}SelectionSet(include);
    const query = `query Get{name}($id: ID!) {{
      {get_q}(id: $id) {{
        ${{fields}}
      }}
    }}`;

    const data = await this.transport.request<{{ {get_q}: {name} | null }}>(query, {{ id }});
    return data.{get_q};
  }}

  public async create(input: {name}Input, include?: {name}Include): Promise<{name}> {{
    const fields = build{name}SelectionSet(include);
    const query = `mutation Mutate{name}($input: {name}Input!) {{
      {create_m}(input: $input) {{
        result {{
          ${{fields}}
        }}
        errors {{
          field
          message
        }}
        success
      }}
    }}`;

    const data = await this.transport.request<{{
      {create_m}: {{
        result?: {name};
        errors: AshUserError[];
        success: boolean;
      }};
    }}>(query, {{ input }});

    const payload = data.{create_m};
    if (!payload.success || !payload.result) {{
      throw new AshClientError(payload.errors[0]?.message || "Create failed", payload.errors);
    }}

    return payload.result;
  }}

  public async update(id: string, input: Partial<{name}Input>, include?: {name}Include): Promise<{name}> {{
    const fields = build{name}SelectionSet(include);
    const query = `mutation Mutate{name}($id: ID!, $input: {name}Input!) {{
      {update_m}(id: $id, input: $input) {{
        result {{
          ${{fields}}
        }}
        errors {{
          field
          message
        }}
        success
      }}
    }}`;

    const data = await this.transport.request<{{
      {update_m}: {{
        result?: {name};
        errors: AshUserError[];
        success: boolean;
      }};
    }}>(query, {{ id, input }});

    const payload = data.{update_m};
    if (!payload.success || !payload.result) {{
      throw new AshClientError(payload.errors[0]?.message || "Update failed", payload.errors);
    }}

    return payload.result;
  }}

  public async destroy(id: string): Promise<boolean> {{
    const query = `mutation Mutate{name}($id: ID!) {{
      {destroy_m}(id: $id) {{
        errors {{
          field
          message
        }}
        success
      }}
    }}`;

    const data = await this.transport.request<{{
      {destroy_m}: {{
        errors: AshUserError[];
        success: boolean;
      }};
    }}>(query, {{ id }});

    const payload = data.{destroy_m};
    if (!payload.success) {{
      throw new AshClientError(payload.errors[0]?.message || "Destroy failed", payload.errors);
    }}

    return true;
  }}
}}

"#
            ));
        }

        // Root client
        out.push_str(&format!("export class {} {{\n", config.client_class_name));
        out.push_str("  public readonly transport: AshTransport;\n");
        for s in snapshots {
            let res_name = &table_to_res[s.table.as_str()];
            let prop = to_camel_case(res_name);
            out.push_str(&format!("  public readonly {prop}: {res_name}Client;\n"));
        }
        out.push_str("\n  constructor(config: AshClientConfig) {\n");
        out.push_str("    this.transport = new AshTransport(config);\n");
        for s in snapshots {
            let res_name = &table_to_res[s.table.as_str()];
            let prop = to_camel_case(res_name);
            out.push_str(&format!("    this.{prop} = new {res_name}Client(this.transport);\n"));
        }
        out.push_str("  }\n}\n\n");

        out.push_str(&format!(
            "export function create{}(config: AshClientConfig): {} {{\n  return new {}(config);\n}}\n",
            config.client_class_name, config.client_class_name, config.client_class_name
        ));
    }

    Ok(out)
}
