//! Code generation from `ash-sql` table snapshots.

use std::collections::HashMap;
use ash_sql::TableSnapshot;

use crate::config::TypeScriptConfig;
use crate::generator::CodegenError;
use crate::types::{generate_common_types, to_camel_case, to_pascal_case};

/// Deduce a singular PascalCase resource name from a database table name.
pub fn table_to_resource_name(table: &str) -> String {
    let singular = if let Some(stripped) = table.strip_suffix("ies") {
        format!("{stripped}y")
    } else if let Some(stripped) = table.strip_suffix("sses") {
        format!("{stripped}ss")
    } else if let Some(stripped) = table.strip_suffix('s') {
        if stripped.ends_with('s') {
            table.to_string()
        } else {
            stripped.to_string()
        }
    } else {
        table.to_string()
    };
    to_pascal_case(&singular)
}

/// Map a SQL column type to TypeScript type, Filter type, and Zod validator.
///
/// The Filter type is `None` for JSON columns, which GraphQL cannot filter on.
pub fn sql_type_to_ts_and_zod(
    sql_type: &str,
    nullable: bool,
) -> (&'static str, Option<&'static str>, String) {
    let upper = sql_type.to_ascii_uppercase();
    let (ts_type, filter_type, base_zod) = if upper.contains("UUID") {
        ("string", Some("AshFilter<string>"), "z.string().uuid()")
    } else if upper.contains("INT") || upper.contains("SERIAL") {
        ("number", Some("AshFilter<number>"), "z.number().int()")
    } else if upper.contains("BOOL") {
        ("boolean", Some("AshFilter<boolean>"), "z.boolean()")
    } else if upper.contains("NUMERIC") || upper.contains("DECIMAL") {
        // Decimals travel as strings, like GraphQL's Decimal fields.
        ("string", Some("AshFilter<string>"), "z.string()")
    } else if upper.contains("FLOAT") || upper.contains("DOUBLE") || upper.contains("REAL") {
        ("number", Some("AshFilter<number>"), "z.number()")
    } else if upper.contains("BYTEA") || upper.contains("BLOB") {
        ("string", Some("AshFilter<string>"), "z.string()")
    } else if upper.starts_with("VECTOR") {
        // GraphQL returns embeddings as float lists and has no filter for them.
        ("number[]", None, "z.array(z.number())")
    } else if upper.contains("JSON") {
        ("Record<string, unknown>", None, "z.record(z.string(), z.unknown())")
    } else if upper.contains("CITEXT") || upper.contains("NOCASE") {
        // Only CiString columns are certainly text: SQLite also stores dates, decimals
        // and enums as TEXT, and GraphQL gives those no text filters.
        ("string", Some("AshTextFilter"), "z.string()")
    } else {
        ("string", Some("AshFilter<string>"), "z.string()")
    };

    let zod_str = if nullable {
        format!("{base_zod}.nullable().optional()")
    } else {
        base_zod.to_string()
    };

    (ts_type, filter_type, zod_str)
}

/// Generate consolidated TypeScript SDK from a slice of TableSnapshots.
pub fn generate_from_snapshots(
    snapshots: &[TableSnapshot],
    config: &TypeScriptConfig,
) -> Result<String, CodegenError> {
    if snapshots.is_empty() {
        return Err(CodegenError::EmptyInput);
    }

    let mut out = String::new();
    out.push_str("// ========================================================\n");
    out.push_str("// Automatically generated by cargo ash codegen ts. DO NOT EDIT.\n");
    out.push_str("// ========================================================\n\n");

    if config.generate_zod {
        out.push_str("import { z } from \"zod\";\n\n");
    }

    // 1. Common Types
    out.push_str("// --- Section 1: Common Types & Filters ---\n");
    out.push_str(&generate_common_types());
    out.push('\n');

    // Table to Resource Name map
    let mut table_to_res: HashMap<&str, String> = HashMap::new();
    for s in snapshots {
        table_to_res.insert(&s.table, table_to_resource_name(&s.table));
    }

    // 2. Resource Types
    out.push_str("// --- Section 2: Resource Types & Inputs ---\n");
    for s in snapshots {
        let name = &table_to_res[s.table.as_str()];

        // Model Interface
        out.push_str(&format!("export interface {name} {{\n"));
        for col in &s.columns {
            let (ts_type, _, _) = sql_type_to_ts_and_zod(&col.sql_type, col.nullable);
            if col.nullable {
                out.push_str(&format!("  {}?: {} | null;\n", to_camel_case(&col.name), ts_type));
            } else {
                out.push_str(&format!("  {}: {};\n", to_camel_case(&col.name), ts_type));
            }
        }
        for r in &s.references {
            if let Some(target_res) = table_to_res.get(r.target_table.as_str()) {
                let rel_name = r.column.strip_suffix("_id").unwrap_or(&r.column);
                out.push_str(&format!("  {}?: {} | null;\n", to_camel_case(rel_name), target_res));
            }
        }
        out.push_str("}\n\n");

        // Input Interface (Create/Update)
        out.push_str(&format!("export interface {name}Input {{\n"));
        for col in &s.columns {
            if col.is_primary_key {
                continue;
            }
            let (ts_type, _, _) = sql_type_to_ts_and_zod(&col.sql_type, col.nullable);
            if col.nullable {
                out.push_str(&format!("  {}?: {} | null;\n", to_camel_case(&col.name), ts_type));
            } else {
                out.push_str(&format!("  {}: {};\n", to_camel_case(&col.name), ts_type));
            }
        }
        out.push_str("}\n\n");

        // Filter Input
        out.push_str(&format!("export interface {name}FilterInput {{\n"));
        for col in &s.columns {
            let (_, filter_type, _) = sql_type_to_ts_and_zod(&col.sql_type, col.nullable);
            if let Some(filter_type) = filter_type {
                out.push_str(&format!("  {}?: {};\n", to_camel_case(&col.name), filter_type));
            }
        }
        out.push_str(&format!("  and?: {name}FilterInput[];\n"));
        out.push_str(&format!("  or?: {name}FilterInput[];\n"));
        out.push_str(&format!("  not?: {name}FilterInput[];\n"));
        out.push_str("}\n\n");

        // Sort Input
        let sort_fields = s
            .columns
            .iter()
            .map(|c| format!("\"{}\"", to_camel_case(&c.name)))
            .collect::<Vec<_>>()
            .join(" | ");
        out.push_str(&format!("export type {name}SortField = {sort_fields};\n\n"));
        out.push_str(&format!("export interface {name}SortInput {{\n"));
        out.push_str(&format!("  field: {name}SortField;\n"));
        out.push_str("  order?: SortOrder;\n");
        out.push_str("}\n\n");

        // Include Input
        out.push_str(&format!("export interface {name}Include {{\n"));
        for r in &s.references {
            if let Some(target_res) = table_to_res.get(r.target_table.as_str()) {
                let rel_name = r.column.strip_suffix("_id").unwrap_or(&r.column);
                out.push_str(&format!("  {}?: boolean | {target_res}Include;\n", to_camel_case(rel_name)));
            }
        }
        out.push_str("}\n\n");
    }

    // 3. Zod Schemas
    if config.generate_zod {
        out.push_str("// --- Section 3: Zod Validation Schemas ---\n");
        for s in snapshots {
            let name = &table_to_res[s.table.as_str()];
            out.push_str(&format!("export const {name}Schema = z.object({{\n"));
            for col in &s.columns {
                let (_, _, zod_str) = sql_type_to_ts_and_zod(&col.sql_type, col.nullable);
                out.push_str(&format!("  {}: {},\n", to_camel_case(&col.name), zod_str));
            }
            out.push_str("});\n\n");

            out.push_str(&format!("export const {name}InputSchema = z.object({{\n"));
            for col in &s.columns {
                if col.is_primary_key {
                    continue;
                }
                let (_, _, zod_str) = sql_type_to_ts_and_zod(&col.sql_type, col.nullable);
                out.push_str(&format!("  {}: {},\n", to_camel_case(&col.name), zod_str));
            }
            out.push_str("});\n\n");
        }
    }

    // 4. Client SDK & Selection Set Builders
    if config.generate_client {
        out.push_str("// --- Section 4: Isomorphic Client SDK ---\n");
        out.push_str(&crate::client::generate_transport_runtime(&config.graphql_endpoint, false));
        out.push('\n');

        for s in snapshots {
            let name = &table_to_res[s.table.as_str()];
            let base_attrs = s
                .columns
                .iter()
                .map(|c| to_camel_case(&c.name))
                .collect::<Vec<_>>()
                .join(" ");

            out.push_str(&format!("export function build{name}SelectionSet(include?: {name}Include): string {{\n"));
            out.push_str(&format!("  let fields = \"{base_attrs}\";\n"));
            for r in &s.references {
                if let Some(target_res) = table_to_res.get(r.target_table.as_str()) {
                    let rel_name = to_camel_case(r.column.strip_suffix("_id").unwrap_or(&r.column));
                    out.push_str(&format!("  if (include?.{rel_name}) {{\n"));
                    out.push_str(&format!("    const subInclude = typeof include.{rel_name} === \"object\" ? include.{rel_name} : undefined;\n"));
                    out.push_str(&format!("    fields += ` {rel_name} {{ ${{build{target_res}SelectionSet(subInclude)}} }}`;\n"));
                    out.push_str("  }\n");
                }
            }
            out.push_str("  return fields;\n");
            out.push_str("}\n\n");

            // Query Builder
            let sort_names = s
                .columns
                .iter()
                .map(|c| format!("{}: \"{}\"", to_camel_case(&c.name), c.name.to_ascii_uppercase()))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&crate::client::query_builder_class(
                name,
                &format!("{{ {sort_names} }}"),
                "private readonly transport: AshTransport",
                "",
            ));

            // Client class
            let get_q = crate::client::get_query_name(name);
            let create_m = format!("create{}", name);
            let update_m = format!("update{}", name);
            let destroy_m = format!("destroy{}", name);
            out.push_str(&format!(
                r#"export class {name}Client {{
  constructor(private readonly transport: AshTransport) {{}}

  public query(): {name}QueryBuilder {{
    return new {name}QueryBuilder(this.transport);
  }}

  public async get(id: string, include?: {name}Include): Promise<{name} | null> {{
    const fields = build{name}SelectionSet(include);
    const query = `query Get{name}($id: ID!) {{
      {get_q}(id: $id) {{
        ${{fields}}
      }}
    }}`;

    const data = await this.transport.request<{{ {get_q}: {name} | null }}>(query, {{ id }});
    return data.{get_q};
  }}

  public async create(input: {name}Input, include?: {name}Include): Promise<{name}> {{
    const fields = build{name}SelectionSet(include);
    const query = `mutation Mutate{name}($input: {name}Input!) {{
      {create_m}(input: $input) {{
        result {{
          ${{fields}}
        }}
        errors {{
          message
          shortMessage
          code
          fields
        }}
      }}
    }}`;

    const data = await this.transport.request<{{
      {create_m}: {{
        result?: {name} | null;
        errors: AshUserError[];
      }};
    }}>(query, {{ input }});

    const payload = data.{create_m};
    if (payload.errors.length > 0 || !payload.result) {{
      throw new AshClientError(payload.errors[0]?.message || "Create failed", payload.errors);
    }}

    return payload.result;
  }}

  public async update(id: string, input: Partial<{name}Input>, include?: {name}Include): Promise<{name}> {{
    const fields = build{name}SelectionSet(include);
    const query = `mutation Mutate{name}($id: ID!, $input: {name}Input!) {{
      {update_m}(id: $id, input: $input) {{
        result {{
          ${{fields}}
        }}
        errors {{
          message
          shortMessage
          code
          fields
        }}
      }}
    }}`;

    const data = await this.transport.request<{{
      {update_m}: {{
        result?: {name} | null;
        errors: AshUserError[];
      }};
    }}>(query, {{ id, input }});

    const payload = data.{update_m};
    if (payload.errors.length > 0 || !payload.result) {{
      throw new AshClientError(payload.errors[0]?.message || "Update failed", payload.errors);
    }}

    return payload.result;
  }}

  public async destroy(id: string): Promise<boolean> {{
    const query = `mutation Mutate{name}($id: ID!) {{
      {destroy_m}(id: $id) {{
        errors {{
          message
          shortMessage
          code
          fields
        }}
      }}
    }}`;

    const data = await this.transport.request<{{
      {destroy_m}: {{
        errors: AshUserError[];
      }};
    }}>(query, {{ id }});

    const payload = data.{destroy_m};
    if (payload.errors.length > 0) {{
      throw new AshClientError(payload.errors[0]?.message || "Destroy failed", payload.errors);
    }}

    return true;
  }}
}}

"#
            ));
        }

        // Root client
        out.push_str(&format!("export class {} {{\n", config.client_class_name));
        out.push_str("  public readonly transport: AshTransport;\n");
        for s in snapshots {
            let res_name = &table_to_res[s.table.as_str()];
            let prop = to_camel_case(res_name);
            out.push_str(&format!("  public readonly {prop}: {res_name}Client;\n"));
        }
        out.push_str("\n  constructor(config: AshClientConfig) {\n");
        out.push_str("    this.transport = new AshTransport(config);\n");
        for s in snapshots {
            let res_name = &table_to_res[s.table.as_str()];
            let prop = to_camel_case(res_name);
            out.push_str(&format!("    this.{prop} = new {res_name}Client(this.transport);\n"));
        }
        out.push_str("  }\n}\n\n");

        out.push_str(&format!(
            "export function create{}(config: AshClientConfig): {} {{\n  return new {}(config);\n}}\n",
            config.client_class_name, config.client_class_name, config.client_class_name
        ));
    }

    Ok(out)
}
