use std::any::Any;
use std::collections::HashMap;
use std::future::Future;
use std::marker::PhantomData;
use std::pin::Pin;
use std::sync::Arc;

use crate::changeset::Changeset;
use crate::context::Context;
use crate::data_layer::{DataLayer, TransactionSupport};
use crate::error::{Error, Result};
use crate::resource::Resource;

/// Container for results produced by named steps in a [`Multi`] pipeline.
#[derive(Clone, Default)]
pub struct MultiResult {
    values: HashMap<String, Arc<dyn Any + Send + Sync>>,
}

impl std::fmt::Debug for MultiResult {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MultiResult")
            .field("keys", &self.values.keys().collect::<Vec<_>>())
            .finish()
    }
}

impl MultiResult {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn insert<T: Send + Sync + 'static>(&mut self, name: impl Into<String>, value: T) {
        self.values.insert(name.into(), Arc::new(value));
    }

    pub fn get<T: 'static>(&self, name: &str) -> Result<&T> {
        let arc = self.values.get(name).ok_or_else(|| {
            Error::Invalid(format!("step `{name}` not found in MultiResult"))
        })?;
        arc.downcast_ref::<T>().ok_or_else(|| {
            Error::Invalid(format!(
                "step `{name}` result type mismatch: expected {}",
                std::any::type_name::<T>()
            ))
        })
    }

    pub fn get_arc<T: Send + Sync + 'static>(&self, name: &str) -> Result<Arc<T>> {
        let arc = self.values.get(name).ok_or_else(|| {
            Error::Invalid(format!("step `{name}` not found in MultiResult"))
        })?;
        arc.clone().downcast::<T>().map_err(|_| {
            Error::Invalid(format!(
                "step `{name}` result type mismatch: expected {}",
                std::any::type_name::<T>()
            ))
        })
    }

    pub fn contains(&self, name: &str) -> bool {
        self.values.contains_key(name)
    }

    pub fn len(&self) -> usize {
        self.values.len()
    }

    pub fn is_empty(&self) -> bool {
        self.values.is_empty()
    }
}

/// Trait for types that can be converted into a [`Changeset`].
///
/// Implemented for:
/// - `Changeset<R>` (direct pass-through)
/// - `Result<Changeset<R>>`
/// - Action builders generated by `ash-macros` (e.g. `User::create(&ctx).name("Alice")`)
pub trait IntoChangeset<R: Resource> {
    fn into_changeset(self) -> Result<Changeset<R>>;
}

impl<R: Resource> IntoChangeset<R> for Changeset<R> {
    fn into_changeset(self) -> Result<Changeset<R>> {
        Ok(self)
    }
}

impl<R: Resource> IntoChangeset<R> for Result<Changeset<R>> {
    fn into_changeset(self) -> Result<Changeset<R>> {
        self
    }
}

pub trait Step<D>: Send {
    fn name(&self) -> &str;
    fn execute<'a>(
        &'a mut self,
        ctx: &'a Context<D>,
        results: &'a mut MultiResult,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>>;
}

struct CreateStep<R: Resource> {
    name: String,
    changeset: Option<Result<Changeset<R>>>,
}

impl<D: DataLayer, R: Resource> Step<D> for CreateStep<R> {
    fn name(&self) -> &str {
        &self.name
    }

    fn execute<'a>(
        &'a mut self,
        ctx: &'a Context<D>,
        results: &'a mut MultiResult,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>> {
        Box::pin(async move {
            let cs_res = self.changeset.take().ok_or_else(|| {
                Error::Invalid(format!("step `{}` has already been executed", self.name))
            })?;
            let cs = cs_res?;
            let record = cs.commit(ctx).await?;
            results.insert(self.name.clone(), record);
            Ok(())
        })
    }
}

#[allow(clippy::type_complexity)]
struct CreateFromStep<D, R: Resource> {
    name: String,
    func: Option<Box<dyn FnOnce(&Context<D>, &MultiResult) -> Result<Changeset<R>> + Send>>,
    _phantom: PhantomData<fn(&Context<D>) -> R>,
}

impl<D: DataLayer, R: Resource> Step<D> for CreateFromStep<D, R> {
    fn name(&self) -> &str {
        &self.name
    }

    fn execute<'a>(
        &'a mut self,
        ctx: &'a Context<D>,
        results: &'a mut MultiResult,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>> {
        Box::pin(async move {
            let f = self.func.take().ok_or_else(|| {
                Error::Invalid(format!("step `{}` has already been executed", self.name))
            })?;
            let cs = f(ctx, results)?;
            let record = cs.commit(ctx).await?;
            results.insert(self.name.clone(), record);
            Ok(())
        })
    }
}

struct UpdateStep<R: Resource> {
    name: String,
    changeset: Option<Result<Changeset<R>>>,
}

impl<D: DataLayer, R: Resource> Step<D> for UpdateStep<R> {
    fn name(&self) -> &str {
        &self.name
    }

    fn execute<'a>(
        &'a mut self,
        ctx: &'a Context<D>,
        results: &'a mut MultiResult,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>> {
        Box::pin(async move {
            let cs_res = self.changeset.take().ok_or_else(|| {
                Error::Invalid(format!("step `{}` has already been executed", self.name))
            })?;
            let cs = cs_res?;
            let record = cs.commit(ctx).await?;
            results.insert(self.name.clone(), record);
            Ok(())
        })
    }
}

#[allow(clippy::type_complexity)]
struct UpdateFromStep<D, R: Resource> {
    name: String,
    func: Option<Box<dyn FnOnce(&Context<D>, &MultiResult) -> Result<Changeset<R>> + Send>>,
    _phantom: PhantomData<fn(&Context<D>) -> R>,
}

impl<D: DataLayer, R: Resource> Step<D> for UpdateFromStep<D, R> {
    fn name(&self) -> &str {
        &self.name
    }

    fn execute<'a>(
        &'a mut self,
        ctx: &'a Context<D>,
        results: &'a mut MultiResult,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>> {
        Box::pin(async move {
            let f = self.func.take().ok_or_else(|| {
                Error::Invalid(format!("step `{}` has already been executed", self.name))
            })?;
            let cs = f(ctx, results)?;
            let record = cs.commit(ctx).await?;
            results.insert(self.name.clone(), record);
            Ok(())
        })
    }
}

struct DestroyStep<R: Resource> {
    name: String,
    action: &'static str,
    record: Option<R>,
}

impl<D: DataLayer, R: Resource> Step<D> for DestroyStep<R> {
    fn name(&self) -> &str {
        &self.name
    }

    fn execute<'a>(
        &'a mut self,
        ctx: &'a Context<D>,
        results: &'a mut MultiResult,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>> {
        Box::pin(async move {
            let record = self.record.take().ok_or_else(|| {
                Error::Invalid(format!("step `{}` has already been executed", self.name))
            })?;
            crate::engine::destroy_existing(ctx, self.action, record.clone()).await?;
            results.insert(self.name.clone(), record);
            Ok(())
        })
    }
}

struct DestroyFromStep<D, R, F> {
    name: String,
    action: &'static str,
    func: Option<F>,
    _phantom: PhantomData<fn(&Context<D>) -> R>,
}

impl<D: DataLayer, R: Resource, F> Step<D> for DestroyFromStep<D, R, F>
where
    F: FnOnce(&Context<D>, &MultiResult) -> Result<R> + Send + 'static,
{
    fn name(&self) -> &str {
        &self.name
    }

    fn execute<'a>(
        &'a mut self,
        ctx: &'a Context<D>,
        results: &'a mut MultiResult,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>> {
        Box::pin(async move {
            let f = self.func.take().ok_or_else(|| {
                Error::Invalid(format!("step `{}` has already been executed", self.name))
            })?;
            let record = f(ctx, results)?;
            crate::engine::destroy_existing(ctx, self.action, record.clone()).await?;
            results.insert(self.name.clone(), record);
            Ok(())
        })
    }
}

struct InsertStep<T> {
    name: String,
    value: Option<T>,
}

impl<D: DataLayer, T: Send + Sync + 'static> Step<D> for InsertStep<T> {
    fn name(&self) -> &str {
        &self.name
    }

    fn execute<'a>(
        &'a mut self,
        _ctx: &'a Context<D>,
        results: &'a mut MultiResult,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>> {
        Box::pin(async move {
            let value = self.value.take().ok_or_else(|| {
                Error::Invalid(format!("step `{}` has already been executed", self.name))
            })?;
            results.insert(self.name.clone(), value);
            Ok(())
        })
    }
}

struct RunSyncStep<D, T, F> {
    name: String,
    func: Option<F>,
    _phantom: PhantomData<fn(&Context<D>) -> T>,
}

impl<D: DataLayer, T: Send + Sync + 'static, F> Step<D> for RunSyncStep<D, T, F>
where
    F: FnOnce(&Context<D>, &MultiResult) -> Result<T> + Send + 'static,
{
    fn name(&self) -> &str {
        &self.name
    }

    fn execute<'a>(
        &'a mut self,
        ctx: &'a Context<D>,
        results: &'a mut MultiResult,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>> {
        Box::pin(async move {
            let f = self.func.take().ok_or_else(|| {
                Error::Invalid(format!("step `{}` has already been executed", self.name))
            })?;
            let value = f(ctx, results)?;
            results.insert(self.name.clone(), value);
            Ok(())
        })
    }
}

#[allow(clippy::type_complexity)]
struct RunAsyncStep<D> {
    name: String,
    func: Option<
        Box<
            dyn FnOnce(
                    Context<D>,
                    MultiResult,
                ) -> Pin<
                    Box<dyn Future<Output = Result<Arc<dyn Any + Send + Sync>>> + Send>,
                > + Send,
        >,
    >,
    _phantom: PhantomData<fn(&Context<D>)>,
}

impl<D: DataLayer + 'static> Step<D> for RunAsyncStep<D> {
    fn name(&self) -> &str {
        &self.name
    }

    fn execute<'a>(
        &'a mut self,
        ctx: &'a Context<D>,
        results: &'a mut MultiResult,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>> {
        let f = self.func.take().unwrap();
        let ctx = ctx.clone();
        let res_clone = results.clone();
        Box::pin(async move {
            let val = f(ctx, res_clone).await?;
            results.values.insert(self.name.clone(), val);
            Ok(())
        })
    }
}

/// A pipeline of named operations that execute atomically.
///
/// In the spirit of `Ash.Multi`, operations are defined sequentially and,
/// when executed against a transactional data layer, run within a single
/// database transaction. If any step fails, the entire transaction is rolled back.
pub struct Multi<D> {
    steps: Vec<Box<dyn Step<D>>>,
}

impl<D: DataLayer + 'static> Default for Multi<D> {
    fn default() -> Self {
        Self::new()
    }
}

impl<D: DataLayer + 'static> Multi<D> {
    pub fn new() -> Self {
        Self { steps: Vec::new() }
    }

    /// Add a create operation using a [`Changeset`], `Result<Changeset>`, or direct action builder.
    pub fn create<R: Resource>(
        mut self,
        name: impl Into<String>,
        changeset: impl IntoChangeset<R>,
    ) -> Self {
        self.steps.push(Box::new(CreateStep {
            name: name.into(),
            changeset: Some(changeset.into_changeset()),
        }));
        self
    }

    /// Add a dynamic create operation where the operation is computed from prior step results.
    pub fn create_from<R, C, F>(mut self, name: impl Into<String>, func: F) -> Self
    where
        R: Resource,
        C: IntoChangeset<R>,
        F: FnOnce(&Context<D>, &MultiResult) -> C + Send + 'static,
    {
        self.steps.push(Box::new(CreateFromStep {
            name: name.into(),
            func: Some(Box::new(move |ctx, res| func(ctx, res).into_changeset())),
            _phantom: PhantomData,
        }));
        self
    }

    /// Add an update operation using a [`Changeset`], `Result<Changeset>`, or direct action builder.
    pub fn update<R: Resource>(
        mut self,
        name: impl Into<String>,
        changeset: impl IntoChangeset<R>,
    ) -> Self {
        self.steps.push(Box::new(UpdateStep {
            name: name.into(),
            changeset: Some(changeset.into_changeset()),
        }));
        self
    }

    /// Add a dynamic update operation where the operation is computed from prior step results.
    pub fn update_from<R, C, F>(mut self, name: impl Into<String>, func: F) -> Self
    where
        R: Resource,
        C: IntoChangeset<R>,
        F: FnOnce(&Context<D>, &MultiResult) -> C + Send + 'static,
    {
        self.steps.push(Box::new(UpdateFromStep {
            name: name.into(),
            func: Some(Box::new(move |ctx, res| func(ctx, res).into_changeset())),
            _phantom: PhantomData,
        }));
        self
    }

    /// Add a destroy operation for an existing record.
    pub fn destroy<R: Resource>(
        mut self,
        name: impl Into<String>,
        action: &'static str,
        record: R,
    ) -> Self {
        self.steps.push(Box::new(DestroyStep {
            name: name.into(),
            action,
            record: Some(record),
        }));
        self
    }

    /// Add a dynamic destroy operation where the record is computed from prior step results.
    pub fn destroy_from<R, F>(
        mut self,
        name: impl Into<String>,
        action: &'static str,
        func: F,
    ) -> Self
    where
        R: Resource,
        F: FnOnce(&Context<D>, &MultiResult) -> Result<R> + Send + 'static,
    {
        self.steps.push(Box::new(DestroyFromStep {
            name: name.into(),
            action,
            func: Some(func),
            _phantom: PhantomData,
        }));
        self
    }

    /// Insert an arbitrary value directly into the result map under `name`.
    pub fn insert<T: Send + Sync + 'static>(mut self, name: impl Into<String>, value: T) -> Self {
        self.steps.push(Box::new(InsertStep {
            name: name.into(),
            value: Some(value),
        }));
        self
    }

    /// Add a synchronous custom function step.
    pub fn run_fn<T, F>(mut self, name: impl Into<String>, func: F) -> Self
    where
        T: Send + Sync + 'static,
        F: FnOnce(&Context<D>, &MultiResult) -> Result<T> + Send + 'static,
    {
        self.steps.push(Box::new(RunSyncStep {
            name: name.into(),
            func: Some(func),
            _phantom: PhantomData,
        }));
        self
    }

    /// Add an asynchronous custom function step.
    pub fn run<T, F, Fut>(mut self, name: impl Into<String>, func: F) -> Self
    where
        T: Send + Sync + 'static,
        F: FnOnce(Context<D>, MultiResult) -> Fut + Send + 'static,
        Fut: Future<Output = Result<T>> + Send + 'static,
    {
        let name_str = name.into();
        self.steps.push(Box::new(RunAsyncStep {
            name: name_str,
            func: Some(Box::new(move |ctx: Context<D>, results: MultiResult| {
                Box::pin(async move {
                    let val = func(ctx, results).await?;
                    Ok(Arc::new(val) as Arc<dyn Any + Send + Sync>)
                })
                    as Pin<Box<dyn Future<Output = Result<Arc<dyn Any + Send + Sync>>> + Send>>
            })),
            _phantom: PhantomData,
        }));
        self
    }

    /// Internal execution of all steps sequentially without wrapping in an outer transaction.
    pub async fn run_pipeline(&mut self, ctx: &Context<D>) -> Result<MultiResult> {
        let mut results = MultiResult::new();
        for step in &mut self.steps {
            let step_name = step.name().to_string();
            if let Err(source) = step.execute(ctx, &mut results).await {
                return Err(Error::Multi {
                    step: step_name,
                    source: Box::new(source),
                });
            }
        }
        Ok(results)
    }

    /// Execute the pipeline without starting a transaction.
    pub async fn execute_without_transaction(mut self, ctx: &Context<D>) -> Result<MultiResult> {
        let (buffered_ctx, queue) = ctx.with_notification_buffer();
        let result = self.run_pipeline(&buffered_ctx).await?;

        let queued = {
            let mut q = queue.lock().unwrap();
            std::mem::take(&mut *q)
        };
        for item in queued {
            for notifier in &ctx.notifiers {
                let _ = notifier.notify(&item.notification).await;
            }
            for notifier in item.resource_notifiers {
                let _ = notifier.notify(&item.notification).await;
            }
        }

        Ok(result)
    }
}

impl<D: TransactionSupport + 'static> Multi<D> {
    /// Execute the multi pipeline inside a transaction.
    ///
    /// If any step fails, the entire transaction is rolled back, queued notifications
    /// are discarded, and `Error::Multi` is returned indicating which step failed.
    ///
    /// If and only if all steps succeed and the transaction commits, all accumulated
    /// notifications are dispatched sequentially.
    pub async fn execute(mut self, ctx: &Context<D>) -> Result<MultiResult> {
        let (buffered_ctx, queue) = ctx.with_notification_buffer();
        let queue_clone = Arc::clone(&queue);
        let result = buffered_ctx
            .transaction(move |tx_ctx| {
                let tx_buffered =
                    tx_ctx.with_existing_notification_buffer(Arc::clone(&queue_clone));
                async move { self.run_pipeline(&tx_buffered).await }
            })
            .await?;

        // Transaction successfully committed! Dispatch all accumulated notifications.
        let queued = {
            let mut q = queue.lock().unwrap();
            std::mem::take(&mut *q)
        };
        for item in queued {
            for notifier in &ctx.notifiers {
                let _ = notifier.notify(&item.notification).await;
            }
            for notifier in item.resource_notifiers {
                let _ = notifier.notify(&item.notification).await;
            }
        }

        Ok(result)
    }

    /// Alias for [`execute`](Self::execute) in the spirit of `Changeset::commit`.
    pub async fn commit(self, ctx: &Context<D>) -> Result<MultiResult> {
        self.execute(ctx).await
    }
}

/// A [`Multi`] pipeline bound to an execution [`Context`].
///
/// Created via `ctx.multi()`. Allows building and committing an atomic pipeline
/// in a single fluid chain without needing to pass `&ctx` again at commit time.
pub struct BoundMulti<D> {
    ctx: Context<D>,
    multi: Multi<D>,
}

impl<D: DataLayer + 'static> BoundMulti<D> {
    pub fn new(ctx: Context<D>) -> Self {
        Self {
            ctx,
            multi: Multi::new(),
        }
    }

    /// Add a create operation using a [`Changeset`], `Result<Changeset>`, or direct action builder.
    pub fn create<R: Resource>(mut self, name: impl Into<String>, op: impl IntoChangeset<R>) -> Self {
        self.multi = self.multi.create(name, op);
        self
    }

    /// Add a dynamic create operation where the operation is computed from prior step results.
    pub fn create_from<R, C, F>(mut self, name: impl Into<String>, func: F) -> Self
    where
        R: Resource,
        C: IntoChangeset<R>,
        F: FnOnce(&Context<D>, &MultiResult) -> C + Send + 'static,
    {
        self.multi = self.multi.create_from(name, func);
        self
    }

    /// Add an update operation using a [`Changeset`], `Result<Changeset>`, or direct action builder.
    pub fn update<R: Resource>(mut self, name: impl Into<String>, op: impl IntoChangeset<R>) -> Self {
        self.multi = self.multi.update(name, op);
        self
    }

    /// Add a dynamic update operation where the operation is computed from prior step results.
    pub fn update_from<R, C, F>(mut self, name: impl Into<String>, func: F) -> Self
    where
        R: Resource,
        C: IntoChangeset<R>,
        F: FnOnce(&Context<D>, &MultiResult) -> C + Send + 'static,
    {
        self.multi = self.multi.update_from(name, func);
        self
    }

    /// Add a destroy operation for an existing record.
    pub fn destroy<R: Resource>(
        mut self,
        name: impl Into<String>,
        action: &'static str,
        record: R,
    ) -> Self {
        self.multi = self.multi.destroy(name, action, record);
        self
    }

    /// Add a dynamic destroy operation where the record is computed from prior step results.
    pub fn destroy_from<R, F>(
        mut self,
        name: impl Into<String>,
        action: &'static str,
        func: F,
    ) -> Self
    where
        R: Resource,
        F: FnOnce(&Context<D>, &MultiResult) -> Result<R> + Send + 'static,
    {
        self.multi = self.multi.destroy_from(name, action, func);
        self
    }

    /// Insert an arbitrary value directly into the result map under `name`.
    pub fn insert<T: Send + Sync + 'static>(mut self, name: impl Into<String>, value: T) -> Self {
        self.multi = self.multi.insert(name, value);
        self
    }

    /// Add a synchronous custom function step.
    pub fn run_fn<T, F>(mut self, name: impl Into<String>, func: F) -> Self
    where
        T: Send + Sync + 'static,
        F: FnOnce(&Context<D>, &MultiResult) -> Result<T> + Send + 'static,
    {
        self.multi = self.multi.run_fn(name, func);
        self
    }

    /// Add an asynchronous custom function step.
    pub fn run<T, F, Fut>(mut self, name: impl Into<String>, func: F) -> Self
    where
        T: Send + Sync + 'static,
        F: FnOnce(Context<D>, MultiResult) -> Fut + Send + 'static,
        Fut: Future<Output = Result<T>> + Send + 'static,
    {
        self.multi = self.multi.run(name, func);
        self
    }

    /// Unbind and return the underlying [`Multi`] pipeline.
    pub fn into_multi(self) -> Multi<D> {
        self.multi
    }

    /// Commit the bound pipeline without wrapping in a transaction.
    pub async fn commit_without_transaction(self) -> Result<MultiResult> {
        self.multi.execute_without_transaction(&self.ctx).await
    }
}

impl<D: crate::data_layer::TransactionSupport + 'static> BoundMulti<D> {
    /// Commit the bound pipeline atomically inside a database transaction.
    pub async fn commit(self) -> Result<MultiResult> {
        self.multi.execute(&self.ctx).await
    }
}
