defmodule Helpdesk.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add(
        :representative_id,
        references(:representatives,
          column: :id,
          name: "tickets_representative_id_fkey",
          type: :uuid
        )
      )

      add(:requester_email, :citext)
      add(:attachment, :binary)
      add(:due_on, :date)
      add(:estimate, :float)
      add(:opener_id, :uuid, null: false)
      add(:status, :text, null: false)
      add(:subject, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create table(:representatives, primary_key: false) do
      add(:name, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end
  end

  def down do
    drop(table(:representatives))

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `tickets` table without the `tickets_representative_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop(table(:tickets))
  end
end
