defmodule Kanban.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspaces, primary_key: false) do
      add :owner_id, :uuid, null: false
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:workspace_members, primary_key: false) do
      add :role, :text, null: false

      add :user_id,
          references(:users, column: :id, name: "workspace_members_user_id_fkey", type: :uuid),
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "workspace_members_workspace_id_fkey",
            type: :uuid
          ), null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create table(:users, primary_key: false) do
      add :email, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:lists, primary_key: false) do
      add :archived, :boolean, null: false
      add :position, :bigint, null: false
      add :title, :text, null: false

      add :board_id, references(:boards, column: :id, name: "lists_board_id_fkey", type: :uuid),
        null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create table(:comments, primary_key: false) do
      add :body, :text, null: false
      add :author_id, :uuid

      add :card_id, references(:cards, column: :id, name: "comments_card_id_fkey", type: :uuid),
        null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create table(:checklist_items, primary_key: false) do
      add :position, :bigint, null: false
      add :completed, :boolean, null: false
      add :title, :text, null: false

      add :card_id,
          references(:cards, column: :id, name: "checklist_items_card_id_fkey", type: :uuid),
          null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create table(:cards, primary_key: false) do
      add :assignee_id, :uuid
      add :creator_id, :uuid
      add :archived, :boolean, null: false
      add :requester_email, :citext
      add :attachment, :binary
      add :due_on, :date
      add :estimate, :float
      add :position, :bigint, null: false
      add :description, :text
      add :title, :text, null: false

      add :list_id, references(:lists, column: :id, name: "cards_list_id_fkey", type: :uuid),
        null: false

      add :board_id, references(:boards, column: :id, name: "cards_board_id_fkey", type: :uuid),
        null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create table(:boards, primary_key: false) do
      add :archived, :boolean, null: false
      add :description, :text
      add :name, :text, null: false
      add :workspace_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:boards)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cards` table without the `cards_board_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cards` table without the `cards_list_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:cards)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `checklist_items` table without the `checklist_items_card_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:checklist_items)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `comments` table without the `comments_card_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:comments)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `lists` table without the `lists_board_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:lists)

    drop table(:users)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workspace_members` table without the `workspace_members_workspace_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workspace_members` table without the `workspace_members_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:workspace_members)

    drop table(:workspaces)
  end
end