// Generated by AshTypescript - RPC Actions
// Do not edit this file manually

import { Channel } from "phoenix";

import type { AgentFilterInput, AgentResourceSchema, AgentSortField, AshRpcError, AuditEventFilterInput, AuditEventResourceSchema, AuditEventSortField, CommentFilterInput, CommentResourceSchema, CommentSortField, ConditionalPaginatedResult, InferResult, SortString, TagFilterInput, TagResourceSchema, TagSortField, TicketFilterInput, TicketResourceSchema, TicketSortField, UUID, UnifiedFieldSelection, ValidationResult } from "./ash_types";
export type * from "./ash_types";

// RPC Action Hook Context Type
export type ActionHookContext = RpcHooks.ActionHookContext;

// RPC Validation Hook Context Type
export type ValidationHookContext = RpcHooks.ValidationHookContext;

// RPC Action Channel Hook Context Type
export type ActionChannelHookContext = RpcHooks.ActionChannelHookContext;

// RPC Validation Channel Hook Context Type
export type ValidationChannelHookContext = RpcHooks.ValidationChannelHookContext;

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any> | undefined;
  identity?: any;
  fields?: Array<string | Record<string, any>> | undefined; // Field selection
  filter?: Record<string, any> | undefined; // Filter options (for reads)
  sort?: string | string[] | undefined; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      }
    | undefined;

  // Metadata
  metadataFields?: ReadonlyArray<string> | undefined;

  // HTTP customization
  headers?: Record<string, string> | undefined; // Custom headers
  fetchOptions?: RequestInit | undefined; // Fetch options (signal, cache, etc.)
  customFetch?: ((
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>) | undefined;

  // Multitenancy
  tenant?: string | undefined; // Tenant parameter

  // Hook context
  hookCtx?: RpcHooks.ActionHookContext | undefined;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any> | undefined;

  // HTTP customization
  headers?: Record<string, string> | undefined;
  fetchOptions?: RequestInit | undefined;
  customFetch?: ((
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>) | undefined;

  // Hook context
  hookCtx?: RpcHooks.ValidationHookContext | undefined;
}


/**
 * Configuration options for action channel RPC requests
 */
export interface ActionChannelConfig {
  // Request data
  input?: Record<string, any> | undefined;
  identity?: any;
  fields?: ReadonlyArray<string | Record<string, any>> | undefined;
  filter?: Record<string, any> | undefined;
  sort?: string | string[] | undefined;
  page?:
    | {
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        limit?: number;
        after?: string;
        before?: string;
      }
    | undefined;

  // Metadata
  metadataFields?: ReadonlyArray<string> | undefined;

  // Channel-specific
  channel: any; // Phoenix Channel
  resultHandler: (result: any) => void;
  errorHandler?: ((error: any) => void) | undefined;
  timeoutHandler?: (() => void) | undefined;
  timeout?: number | undefined;

  // Multitenancy
  tenant?: string | undefined;

  // Hook context
  hookCtx?: RpcHooks.ActionChannelHookContext | undefined;
}


/**
 * Configuration options for validation channel RPC requests
 */
export interface ValidationChannelConfig {
  // Request data
  input?: Record<string, any> | undefined;
  identity?: any;

  // Channel-specific
  channel: any; // Phoenix Channel
  resultHandler: (result: any) => void;
  errorHandler?: ((error: any) => void) | undefined;
  timeoutHandler?: (() => void) | undefined;
  timeout?: number | undefined;

  // Multitenancy
  tenant?: string | undefined;

  // Hook context
  hookCtx?: RpcHooks.ValidationChannelHookContext | undefined;
}


/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    let processedConfig = config;
    if (RpcHooks.beforeRequest) {
      processedConfig = await RpcHooks.beforeRequest(payload.action, config);
    }

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;

    if (RpcHooks.afterRequest) {
      await RpcHooks.afterRequest(payload.action, response, result, processedConfig);
    }

  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    let processedConfig = config;
    if (RpcHooks.beforeValidationRequest) {
      processedConfig = await RpcHooks.beforeValidationRequest(payload.action, config);
    }

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;

    if (RpcHooks.afterValidationRequest) {
      await RpcHooks.afterValidationRequest(payload.action, response, result, processedConfig);
    }

  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making action channel push requests
 * Handles hooks and channel push with receive handlers
 * @param config Configuration matching ActionChannelConfig
 */
export async function executeActionChannelPush<T>(
  channel: any,
  payload: Record<string, any>,
  timeout: number | undefined,
  config: ActionChannelConfig
) {
    let processedConfig = config;
    if (RpcHooks.beforeChannelPush) {
      processedConfig = await RpcHooks.beforeChannelPush(payload.action, config);
    }

  const effectiveTimeout = timeout;

  channel
    .push("run", payload, effectiveTimeout)
    .receive("ok", async (result: T) => {
      if (RpcHooks.afterChannelResponse) {
        await RpcHooks.afterChannelResponse(payload.action, "ok", result, processedConfig);
      }

      config.resultHandler(result);
    })
    .receive("error", async (error: any) => {
      if (RpcHooks.afterChannelResponse) {
        await RpcHooks.afterChannelResponse(payload.action, "error", error, processedConfig);
      }

      (config.errorHandler
        ? config.errorHandler
        : (error: any) => {
            console.error(
              `An error occurred while running action ${payload.action}:`,
              error
            );
          })(error);
    })
    .receive("timeout", async () => {
      if (RpcHooks.afterChannelResponse) {
        await RpcHooks.afterChannelResponse(payload.action, "timeout", undefined, processedConfig);
      }

      (config.timeoutHandler
        ? config.timeoutHandler
        : () => {
            console.error(`Timeout occurred while running action ${payload.action}`);
          })();
    });
}


/**
 * Internal helper function for making validation channel push requests
 * Handles hooks and channel push with receive handlers
 * @param config Configuration matching ValidationChannelConfig
 */
export async function executeValidationChannelPush<T>(
  channel: any,
  payload: Record<string, any>,
  timeout: number | undefined,
  config: ValidationChannelConfig
) {
    let processedConfig = config;
    if (RpcHooks.beforeValidationChannelPush) {
      processedConfig = await RpcHooks.beforeValidationChannelPush(payload.action, config);
    }

  const effectiveTimeout = timeout;

  channel
    .push("validate", payload, effectiveTimeout)
    .receive("ok", async (result: T) => {
      if (RpcHooks.afterValidationChannelResponse) {
        await RpcHooks.afterValidationChannelResponse(payload.action, "ok", result, processedConfig);
      }

      config.resultHandler(result);
    })
    .receive("error", async (error: any) => {
      if (RpcHooks.afterValidationChannelResponse) {
        await RpcHooks.afterValidationChannelResponse(payload.action, "error", error, processedConfig);
      }

      (config.errorHandler
        ? config.errorHandler
        : (error: any) => {
            console.error(
              `An error occurred while running action ${payload.action}:`,
              error
            );
          })(error);
    })
    .receive("timeout", async () => {
      if (RpcHooks.afterValidationChannelResponse) {
        await RpcHooks.afterValidationChannelResponse(payload.action, "timeout", undefined, processedConfig);
      }

      (config.timeoutHandler
        ? config.timeoutHandler
        : () => {
            console.error(`Timeout occurred while running action ${payload.action}`);
          })();
    });
}



// ============================
// Typed Queries
// ============================
// Use these types and field constants for server-side rendering and data fetching.
// The field constants can be used with the corresponding RPC actions for client-side refetching.

// Ticket Typed Queries
/**
 * Typed query for Ticket
 *
 * @typedQuery true
 */
export type TicketInboxResult = Array<InferResult<TicketResourceSchema, ["id", "subject", { assignee: ["name"] }]>>;

/**
 * Typed query for Ticket
 *
 * @typedQuery true
 */
export const ticketInbox = ["id", "subject", { assignee: ["name"] }] satisfies ListTicketsFields;


/**
 * Typed query for Ticket
 *
 * @typedQuery true
 */
export type TicketCardResult = Array<InferResult<TicketResourceSchema, ["id", "status"]>>;

/**
 * Typed query for Ticket
 *
 * @typedQuery true
 */
export const ticketCard = ["id", "status"] satisfies ListTicketsFields;




export type ListAgentsFields = UnifiedFieldSelection<AgentResourceSchema>[];


export type InferListAgentsResult<
  Fields extends ListAgentsFields | undefined,
  Page extends ListAgentsConfig["page"] = undefined
> = ConditionalPaginatedResult<Page, Array<InferResult<AgentResourceSchema, Fields>>, {
  results: Array<InferResult<AgentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListAgentsConfig = {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: ListAgentsFields;
  filter?: AgentFilterInput;
  sort?: SortString<AgentSortField> | SortString<AgentSortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListAgentsResult<Fields extends ListAgentsFields, Page extends ListAgentsConfig["page"] = undefined> = | { success: true; data: InferListAgentsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Agent records
 *
 * @ashActionType :read
 */
export async function listAgents<Fields extends ListAgentsFields, Config extends ListAgentsConfig = ListAgentsConfig>(
  config: Config & { fields: Fields }
): Promise<ListAgentsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_agents",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListAgentsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Agent records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListAgents(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_agents",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read Agent records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListAgentsChannel(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_agents",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read Agent records
 *
 * @ashActionType :read
 */
export async function listAgentsChannel<Fields extends ListAgentsFields, Page extends ListAgentsConfig["page"] = undefined>(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ActionChannelHookContext;
  fields: Fields;
  filter?: AgentFilterInput;
  sort?: SortString<AgentSortField> | SortString<AgentSortField>[];
  page?: Page;
  resultHandler: (result: ListAgentsResult<Fields, Page>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListAgentsResult<Fields, Page>>(
    config.channel,
    {
    action: "list_agents",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  },
    config.timeout,
    config
  );
}


export type ListAuditEventsFields = UnifiedFieldSelection<AuditEventResourceSchema>[];


export type InferListAuditEventsResult<
  Fields extends ListAuditEventsFields | undefined,
  Page extends ListAuditEventsConfig["page"] = undefined
> = ConditionalPaginatedResult<Page, Array<InferResult<AuditEventResourceSchema, Fields>>, {
  results: Array<InferResult<AuditEventResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListAuditEventsConfig = {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: ListAuditEventsFields;
  filter?: AuditEventFilterInput;
  sort?: SortString<AuditEventSortField> | SortString<AuditEventSortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListAuditEventsResult<Fields extends ListAuditEventsFields, Page extends ListAuditEventsConfig["page"] = undefined> = | { success: true; data: InferListAuditEventsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read AuditEvent records
 *
 * @ashActionType :read
 */
export async function listAuditEvents<Fields extends ListAuditEventsFields, Config extends ListAuditEventsConfig = ListAuditEventsConfig>(
  config: Config & { fields: Fields }
): Promise<ListAuditEventsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_audit_events",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListAuditEventsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read AuditEvent records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListAuditEvents(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_audit_events",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read AuditEvent records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListAuditEventsChannel(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_audit_events",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read AuditEvent records
 *
 * @ashActionType :read
 */
export async function listAuditEventsChannel<Fields extends ListAuditEventsFields, Page extends ListAuditEventsConfig["page"] = undefined>(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ActionChannelHookContext;
  fields: Fields;
  filter?: AuditEventFilterInput;
  sort?: SortString<AuditEventSortField> | SortString<AuditEventSortField>[];
  page?: Page;
  resultHandler: (result: ListAuditEventsResult<Fields, Page>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListAuditEventsResult<Fields, Page>>(
    config.channel,
    {
    action: "list_audit_events",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  },
    config.timeout,
    config
  );
}


export type CreateCommentInput = {
  ticketId: UUID;
  body: string;
  internal?: boolean;
};

export type CreateCommentFields = UnifiedFieldSelection<CommentResourceSchema>[];

export type InferCreateCommentResult<
  Fields extends CreateCommentFields | undefined,
> = InferResult<CommentResourceSchema, Fields>;

export type CreateCommentResult<Fields extends CreateCommentFields | undefined = undefined> = | { success: true; data: InferCreateCommentResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Comment
 *
 * @ashActionType :create
 */
export async function createComment<Fields extends CreateCommentFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateCommentInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateCommentResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_comment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateCommentResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Comment
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateComment(
  config: {
  tenant?: string;
  input: CreateCommentInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_comment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Comment
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateCommentChannel(config: {
  channel: Channel;
  tenant?: string;
  input: CreateCommentInput;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "create_comment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Create a new Comment
 *
 * @ashActionType :create
 */
export async function createCommentChannel<Fields extends CreateCommentFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  input: CreateCommentInput;
  hookCtx?: ActionChannelHookContext;
  fields?: Fields;
  resultHandler: (result: CreateCommentResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<CreateCommentResult<Fields>>(
    config.channel,
    {
    action: "create_comment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type ListCommentsFields = UnifiedFieldSelection<CommentResourceSchema>[];


export type InferListCommentsResult<
  Fields extends ListCommentsFields | undefined,
  Page extends ListCommentsConfig["page"] = undefined
> = ConditionalPaginatedResult<Page, Array<InferResult<CommentResourceSchema, Fields>>, {
  results: Array<InferResult<CommentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListCommentsConfig = {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: ListCommentsFields;
  filter?: CommentFilterInput;
  sort?: SortString<CommentSortField> | SortString<CommentSortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListCommentsResult<Fields extends ListCommentsFields, Page extends ListCommentsConfig["page"] = undefined> = | { success: true; data: InferListCommentsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Comment records
 *
 * @ashActionType :read
 */
export async function listComments<Fields extends ListCommentsFields, Config extends ListCommentsConfig = ListCommentsConfig>(
  config: Config & { fields: Fields }
): Promise<ListCommentsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_comments",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListCommentsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Comment records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListComments(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_comments",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read Comment records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListCommentsChannel(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_comments",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read Comment records
 *
 * @ashActionType :read
 */
export async function listCommentsChannel<Fields extends ListCommentsFields, Page extends ListCommentsConfig["page"] = undefined>(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ActionChannelHookContext;
  fields: Fields;
  filter?: CommentFilterInput;
  sort?: SortString<CommentSortField> | SortString<CommentSortField>[];
  page?: Page;
  resultHandler: (result: ListCommentsResult<Fields, Page>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListCommentsResult<Fields, Page>>(
    config.channel,
    {
    action: "list_comments",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  },
    config.timeout,
    config
  );
}


export type ListTagsFields = UnifiedFieldSelection<TagResourceSchema>[];


export type InferListTagsResult<
  Fields extends ListTagsFields | undefined,
  Page extends ListTagsConfig["page"] = undefined
> = ConditionalPaginatedResult<Page, Array<InferResult<TagResourceSchema, Fields>>, {
  results: Array<InferResult<TagResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListTagsConfig = {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: ListTagsFields;
  filter?: TagFilterInput;
  sort?: SortString<TagSortField> | SortString<TagSortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListTagsResult<Fields extends ListTagsFields, Page extends ListTagsConfig["page"] = undefined> = | { success: true; data: InferListTagsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Tag records
 *
 * @ashActionType :read
 */
export async function listTags<Fields extends ListTagsFields, Config extends ListTagsConfig = ListTagsConfig>(
  config: Config & { fields: Fields }
): Promise<ListTagsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_tags",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListTagsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Tag records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListTags(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_tags",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read Tag records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListTagsChannel(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_tags",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read Tag records
 *
 * @ashActionType :read
 */
export async function listTagsChannel<Fields extends ListTagsFields, Page extends ListTagsConfig["page"] = undefined>(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ActionChannelHookContext;
  fields: Fields;
  filter?: TagFilterInput;
  sort?: SortString<TagSortField> | SortString<TagSortField>[];
  page?: Page;
  resultHandler: (result: ListTagsResult<Fields, Page>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListTagsResult<Fields, Page>>(
    config.channel,
    {
    action: "list_tags",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  },
    config.timeout,
    config
  );
}


export type AssignTicketInput = {
  assigneeId?: UUID | null;
};

export type AssignTicketFields = UnifiedFieldSelection<TicketResourceSchema>[];

export type InferAssignTicketResult<
  Fields extends AssignTicketFields | undefined,
> = InferResult<TicketResourceSchema, Fields>;

export type AssignTicketResult<Fields extends AssignTicketFields | undefined = undefined> = | { success: true; data: InferAssignTicketResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function assignTicket<Fields extends AssignTicketFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input?: AssignTicketInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<AssignTicketResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "assign_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<AssignTicketResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateAssignTicket(
  config: {
  tenant?: string;
  identity: UUID | string;
  input?: AssignTicketInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "assign_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateAssignTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  input?: AssignTicketInput;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "assign_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function assignTicketChannel<Fields extends AssignTicketFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  input?: AssignTicketInput;
  hookCtx?: ActionChannelHookContext;
  fields?: Fields;
  resultHandler: (result: AssignTicketResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<AssignTicketResult<Fields>>(
    config.channel,
    {
    action: "assign_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type CloseTicketFields = UnifiedFieldSelection<TicketResourceSchema>[];

export type InferCloseTicketResult<
  Fields extends CloseTicketFields | undefined,
> = InferResult<TicketResourceSchema, Fields>;

export type CloseTicketResult<Fields extends CloseTicketFields | undefined = undefined> = | { success: true; data: InferCloseTicketResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function closeTicket<Fields extends CloseTicketFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CloseTicketResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "close_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CloseTicketResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateCloseTicket(
  config: {
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "close_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateCloseTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "close_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function closeTicketChannel<Fields extends CloseTicketFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionChannelHookContext;
  fields?: Fields;
  resultHandler: (result: CloseTicketResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<CloseTicketResult<Fields>>(
    config.channel,
    {
    action: "close_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type DestroyTicketResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Ticket
 *
 * @ashActionType :destroy
 */
export async function destroyTicket(
  config: {
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyTicketResult> {
  const payload = {
    action: "destroy_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyTicketResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Ticket
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyTicket(
  config: {
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "destroy_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Ticket
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "destroy_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Delete a Ticket
 *
 * @ashActionType :destroy
 */
export async function destroyTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionChannelHookContext;
  resultHandler: (result: DestroyTicketResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<DestroyTicketResult>(
    config.channel,
    {
    action: "destroy_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


export type EditTicketInput = {
  subject?: string;
  priority?: number;
};

export type EditTicketFields = UnifiedFieldSelection<TicketResourceSchema>[];

export type InferEditTicketResult<
  Fields extends EditTicketFields | undefined,
> = InferResult<TicketResourceSchema, Fields>;

export type EditTicketResult<Fields extends EditTicketFields | undefined = undefined> = | { success: true; data: InferEditTicketResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function editTicket<Fields extends EditTicketFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input?: EditTicketInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<EditTicketResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "edit_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<EditTicketResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateEditTicket(
  config: {
  tenant?: string;
  identity: UUID | string;
  input?: EditTicketInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "edit_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateEditTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  input?: EditTicketInput;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "edit_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function editTicketChannel<Fields extends EditTicketFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  input?: EditTicketInput;
  hookCtx?: ActionChannelHookContext;
  fields?: Fields;
  resultHandler: (result: EditTicketResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<EditTicketResult<Fields>>(
    config.channel,
    {
    action: "edit_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type HoldTicketFields = UnifiedFieldSelection<TicketResourceSchema>[];

export type InferHoldTicketResult<
  Fields extends HoldTicketFields | undefined,
> = InferResult<TicketResourceSchema, Fields>;

export type HoldTicketResult<Fields extends HoldTicketFields | undefined = undefined> = | { success: true; data: InferHoldTicketResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function holdTicket<Fields extends HoldTicketFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<HoldTicketResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "hold_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<HoldTicketResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateHoldTicket(
  config: {
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "hold_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateHoldTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "hold_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function holdTicketChannel<Fields extends HoldTicketFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionChannelHookContext;
  fields?: Fields;
  resultHandler: (result: HoldTicketResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<HoldTicketResult<Fields>>(
    config.channel,
    {
    action: "hold_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type ListNotedTicketsFields = UnifiedFieldSelection<TicketResourceSchema>[];

export type ListNotedTicketsMetadata = {
  shortId: string;
};


export type InferListNotedTicketsResult<
  Fields extends ListNotedTicketsFields | undefined,
  MetadataFields extends ReadonlyArray<keyof ListNotedTicketsMetadata> = [],
  Page extends ListNotedTicketsConfig["page"] = undefined
> = ConditionalPaginatedResult<Page, Array<InferResult<TicketResourceSchema, Fields> & Pick<ListNotedTicketsMetadata, MetadataFields[number]>>, {
  results: Array<InferResult<TicketResourceSchema, Fields> & Pick<ListNotedTicketsMetadata, MetadataFields[number]>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListNotedTicketsConfig = {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: ListNotedTicketsFields;
  filter?: TicketFilterInput;
  sort?: SortString<TicketSortField> | SortString<TicketSortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  metadataFields?: ReadonlyArray<keyof ListNotedTicketsMetadata>;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListNotedTicketsResult<Fields extends ListNotedTicketsFields, MetadataFields extends ReadonlyArray<keyof ListNotedTicketsMetadata> = [], Page extends ListNotedTicketsConfig["page"] = undefined> = | { success: true; data: InferListNotedTicketsResult<Fields, MetadataFields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Ticket records
 *
 * @ashActionType :read
 */
export async function listNotedTickets<Fields extends ListNotedTicketsFields, Config extends ListNotedTicketsConfig = ListNotedTicketsConfig>(
  config: Config & { fields: Fields }
): Promise<ListNotedTicketsResult<Fields, Config["metadataFields"] extends ReadonlyArray<any> ? Config["metadataFields"] : [], Config["page"]>> {
  const payload = {
    action: "list_noted_tickets",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.metadataFields && { metadataFields: config.metadataFields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListNotedTicketsResult<Fields, Config["metadataFields"] extends ReadonlyArray<any> ? Config["metadataFields"] : [], Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Ticket records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListNotedTickets(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_noted_tickets",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read Ticket records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListNotedTicketsChannel(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_noted_tickets",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read Ticket records
 *
 * @ashActionType :read
 */
export async function listNotedTicketsChannel<Fields extends ListNotedTicketsFields, MetadataFields extends ReadonlyArray<keyof ListNotedTicketsMetadata> = [], Page extends ListNotedTicketsConfig["page"] = undefined>(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ActionChannelHookContext;
  fields: Fields;
  filter?: TicketFilterInput;
  sort?: SortString<TicketSortField> | SortString<TicketSortField>[];
  page?: Page;
  metadataFields?: MetadataFields;
  resultHandler: (result: ListNotedTicketsResult<Fields, MetadataFields, Page>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListNotedTicketsResult<Fields, MetadataFields, Page>>(
    config.channel,
    {
    action: "list_noted_tickets",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.metadataFields && { metadataFields: config.metadataFields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  },
    config.timeout,
    config
  );
}


export type OpenTicketInput = {
  subject: string;
  body: string;
  priority: number;
  confidential?: boolean;
  requesterEmail?: string | null;
  comments?: Array<Record<string, any>> | null;
};

export type OpenTicketFields = UnifiedFieldSelection<TicketResourceSchema>[];

export type OpenTicketMetadata = {
  commentsGiven: number;
};

export type InferOpenTicketResult<
  Fields extends OpenTicketFields | undefined,
  MetadataFields extends ReadonlyArray<keyof OpenTicketMetadata> = []
> = InferResult<TicketResourceSchema, Fields>;

export type OpenTicketResult<Fields extends OpenTicketFields | undefined = undefined, MetadataFields extends ReadonlyArray<keyof OpenTicketMetadata> = []> = | { success: true; data: InferOpenTicketResult<Fields>; metadata: Pick<OpenTicketMetadata, MetadataFields[number]>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Ticket
 *
 * @ashActionType :create
 */
export async function openTicket<Fields extends OpenTicketFields | undefined = undefined, MetadataFields extends ReadonlyArray<keyof OpenTicketMetadata> = []>(
  config: {
  tenant?: string;
  input: OpenTicketInput;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  metadataFields?: MetadataFields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<OpenTicketResult<Fields extends undefined ? [] : Fields, MetadataFields>> {
  const payload = {
    action: "open_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.metadataFields && { metadataFields: config.metadataFields })
  };

  return executeActionRpcRequest<OpenTicketResult<Fields extends undefined ? [] : Fields, MetadataFields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Ticket
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateOpenTicket(
  config: {
  tenant?: string;
  input: OpenTicketInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "open_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Ticket
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateOpenTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  input: OpenTicketInput;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "open_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Create a new Ticket
 *
 * @ashActionType :create
 */
export async function openTicketChannel<Fields extends OpenTicketFields | undefined = undefined, MetadataFields extends ReadonlyArray<keyof OpenTicketMetadata> = []>(config: {
  channel: Channel;
  tenant?: string;
  input: OpenTicketInput;
  hookCtx?: ActionChannelHookContext;
  fields?: Fields;
  metadataFields?: MetadataFields;
  resultHandler: (result: OpenTicketResult<Fields, MetadataFields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<OpenTicketResult<Fields, MetadataFields>>(
    config.channel,
    {
    action: "open_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.metadataFields && { metadataFields: config.metadataFields })
  },
    config.timeout,
    config
  );
}


export type ListTicketsFields = UnifiedFieldSelection<TicketResourceSchema>[];


export type InferListTicketsResult<
  Fields extends ListTicketsFields | undefined,
  Page extends ListTicketsConfig["page"] = undefined
> = ConditionalPaginatedResult<Page, Array<InferResult<TicketResourceSchema, Fields>>, {
  results: Array<InferResult<TicketResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListTicketsConfig = {
  tenant?: string;
  hookCtx?: ActionHookContext;
  fields: ListTicketsFields;
  filter?: TicketFilterInput;
  sort?: SortString<TicketSortField> | SortString<TicketSortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListTicketsResult<Fields extends ListTicketsFields, Page extends ListTicketsConfig["page"] = undefined> = | { success: true; data: InferListTicketsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Ticket records
 *
 * @ashActionType :read
 */
export async function listTickets<Fields extends ListTicketsFields, Config extends ListTicketsConfig = ListTicketsConfig>(
  config: Config & { fields: Fields }
): Promise<ListTicketsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_tickets",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListTicketsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Ticket records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListTickets(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_tickets",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read Ticket records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListTicketsChannel(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_tickets",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read Ticket records
 *
 * @ashActionType :read
 */
export async function listTicketsChannel<Fields extends ListTicketsFields, Page extends ListTicketsConfig["page"] = undefined>(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ActionChannelHookContext;
  fields: Fields;
  filter?: TicketFilterInput;
  sort?: SortString<TicketSortField> | SortString<TicketSortField>[];
  page?: Page;
  resultHandler: (result: ListTicketsResult<Fields, Page>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListTicketsResult<Fields, Page>>(
    config.channel,
    {
    action: "list_tickets",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  },
    config.timeout,
    config
  );
}


export type GetTicketFields = UnifiedFieldSelection<TicketResourceSchema>[];
export type InferGetTicketResult<
  Fields extends GetTicketFields,
> = InferResult<TicketResourceSchema, Fields>;

export type GetTicketResult<Fields extends GetTicketFields> = | { success: true; data: InferGetTicketResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Ticket records
 *
 * @ashActionType :read
 */
export async function getTicket<Fields extends GetTicketFields>(
  config: {
  tenant?: string;
  hookCtx?: ActionHookContext;
  getBy: {
    id: UUID;
  };
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetTicketResult<Fields>> {
  const payload = {
    action: "get_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    getBy: config.getBy,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetTicketResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Ticket records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetTicket(
  config: {
  tenant?: string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read Ticket records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "get_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read Ticket records
 *
 * @ashActionType :read
 */
export async function getTicketChannel<Fields extends GetTicketFields>(config: {
  channel: Channel;
  tenant?: string;
  hookCtx?: ActionChannelHookContext;
  getBy: {
    id: UUID;
  };
  fields: Fields;
  resultHandler: (result: GetTicketResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<GetTicketResult<Fields>>(
    config.channel,
    {
    action: "get_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    getBy: config.getBy,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type ReopenTicketFields = UnifiedFieldSelection<TicketResourceSchema>[];

export type InferReopenTicketResult<
  Fields extends ReopenTicketFields | undefined,
> = InferResult<TicketResourceSchema, Fields>;

export type ReopenTicketResult<Fields extends ReopenTicketFields | undefined = undefined> = | { success: true; data: InferReopenTicketResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function reopenTicket<Fields extends ReopenTicketFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ReopenTicketResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "reopen_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ReopenTicketResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateReopenTicket(
  config: {
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "reopen_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateReopenTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "reopen_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function reopenTicketChannel<Fields extends ReopenTicketFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionChannelHookContext;
  fields?: Fields;
  resultHandler: (result: ReopenTicketResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ReopenTicketResult<Fields>>(
    config.channel,
    {
    action: "reopen_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type ResolveTicketFields = UnifiedFieldSelection<TicketResourceSchema>[];

export type InferResolveTicketResult<
  Fields extends ResolveTicketFields | undefined,
> = InferResult<TicketResourceSchema, Fields>;

export type ResolveTicketResult<Fields extends ResolveTicketFields | undefined = undefined> = | { success: true; data: InferResolveTicketResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function resolveTicket<Fields extends ResolveTicketFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ResolveTicketResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "resolve_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ResolveTicketResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateResolveTicket(
  config: {
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "resolve_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateResolveTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "resolve_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function resolveTicketChannel<Fields extends ResolveTicketFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionChannelHookContext;
  fields?: Fields;
  resultHandler: (result: ResolveTicketResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ResolveTicketResult<Fields>>(
    config.channel,
    {
    action: "resolve_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type RouteTicketInput = {
  subject: string;
  body: string;
  priority: number;
  requesterEmail: string;
  comments?: Array<Record<string, any>> | null;
};

export type InferRouteTicketResult = UUID;

export type RouteTicketResult = | { success: true; data: InferRouteTicketResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Ticket
 *
 * @ashActionType :action
 */
export async function routeTicket(
  config: {
  tenant?: string;
  input: RouteTicketInput;
  hookCtx?: ActionHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RouteTicketResult> {
  const payload = {
    action: "route_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<RouteTicketResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Ticket
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRouteTicket(
  config: {
  tenant?: string;
  input: RouteTicketInput;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "route_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Ticket
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRouteTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  input: RouteTicketInput;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "route_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Execute generic action on Ticket
 *
 * @ashActionType :action
 */
export async function routeTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  input: RouteTicketInput;
  hookCtx?: ActionChannelHookContext;
  resultHandler: (result: RouteTicketResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<RouteTicketResult>(
    config.channel,
    {
    action: "route_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


export type StartTicketFields = UnifiedFieldSelection<TicketResourceSchema>[];

export type InferStartTicketResult<
  Fields extends StartTicketFields | undefined,
> = InferResult<TicketResourceSchema, Fields>;

export type StartTicketResult<Fields extends StartTicketFields | undefined = undefined> = | { success: true; data: InferStartTicketResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function startTicket<Fields extends StartTicketFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<StartTicketResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "start_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<StartTicketResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateStartTicket(
  config: {
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "start_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateStartTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "start_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function startTicketChannel<Fields extends StartTicketFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionChannelHookContext;
  fields?: Fields;
  resultHandler: (result: StartTicketResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<StartTicketResult<Fields>>(
    config.channel,
    {
    action: "start_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type ViewTicketFields = UnifiedFieldSelection<TicketResourceSchema>[];

export type InferViewTicketResult<
  Fields extends ViewTicketFields | undefined,
> = InferResult<TicketResourceSchema, Fields>;

export type ViewTicketResult<Fields extends ViewTicketFields | undefined = undefined> = | { success: true; data: InferViewTicketResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function viewTicket<Fields extends ViewTicketFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionHookContext;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ViewTicketResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "view_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ViewTicketResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateViewTicket(
  config: {
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationHookContext;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "view_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Ticket
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateViewTicketChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  hookCtx?: ValidationChannelHookContext;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "view_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing Ticket
 *
 * @ashActionType :update
 */
export async function viewTicketChannel<Fields extends ViewTicketFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  hookCtx?: ActionChannelHookContext;
  fields?: Fields;
  resultHandler: (result: ViewTicketResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ViewTicketResult<Fields>>(
    config.channel,
    {
    action: "view_ticket",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}

