defmodule Cybercab.Repo.Migrations.TripsByCab do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:trips, [:cab_id, :requested_at], name: "trips_by_cab_requested")
  end

  def down do
    drop_if_exists(index(:trips, [:cab_id, :requested_at], name: "trips_by_cab_requested"))
  end
end
