defmodule Cybercab.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cabs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:call_sign, :text, null: false)
      add(:nickname, :text, null: false)
      add(:vin, :text, null: false)
      add(:software, :text, null: false)
      add(:lng, :float, null: false)
      add(:lat, :float, null: false)
      add(:heading_deg, :bigint, null: false)
      add(:speed_kph, :bigint, null: false)
      add(:battery_pct, :bigint, null: false)
      add(:range_km, :bigint, null: false)
      add(:odometer_km, :float, null: false)
      add(:cabin_temp_c, :float, null: false)
      add(:halted, :boolean, null: false, default: false)
      add(:last_seen_at, :utc_datetime_usec)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:status, :text, null: false, default: "available")
      add(:depot_id, :uuid, null: false)
    end

    create unique_index(:cabs, [:call_sign], name: "cabs_unique_call_sign_index")

    create unique_index(:cabs, [:vin], name: "cabs_unique_vin_index")

    alter table(:cabs) do
      add(:trip_id, :uuid)
    end

    create table(:depots, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:cabs) do
      modify(
        :depot_id,
        references(:depots,
          column: :id,
          name: "cabs_depot_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:depots) do
      add(:code, :text, null: false)
      add(:name, :text, null: false)
      add(:lng, :float, null: false)
      add(:lat, :float, null: false)
      add(:stalls, :bigint, null: false)
    end

    create unique_index(:depots, [:code], name: "depots_unique_code_index")

    create table(:fleet_alerts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:kind, :text, null: false)
      add(:severity, :text, null: false)
      add(:message, :text, null: false)
      add(:lng, :float, null: false)
      add(:lat, :float, null: false)
      add(:raised_at, :utc_datetime_usec, null: false)
      add(:acknowledged_at, :utc_datetime_usec)
      add(:resolved_at, :utc_datetime_usec)
      add(:handled_by, :text)
      add(:status, :text, null: false, default: "open")

      add(
        :cab_id,
        references(:cabs,
          column: :id,
          name: "fleet_alerts_cab_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:trip_id, :uuid)
    end

    create table(:pulse_samples, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:recorded_at, :utc_datetime_usec, null: false)
      add(:available, :bigint, null: false)
      add(:dispatched, :bigint, null: false)
      add(:on_trip, :bigint, null: false)
      add(:returning, :bigint, null: false)
      add(:charging, :bigint, null: false)
      add(:maintenance, :bigint, null: false)
      add(:waiting, :bigint, null: false)
      add(:completed_today, :bigint, null: false)
      add(:revenue_cents_today, :bigint, null: false)
      add(:avg_wait_s, :bigint, null: false)
      add(:utilization_pct, :bigint, null: false)
      add(:avg_battery_pct, :bigint, null: false)
    end

    create index(:pulse_samples, [:recorded_at], name: "pulse_samples_by_time")

    create table(:riders, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:display_name, :text, null: false)
      add(:tier, :text, null: false)
      add(:rating, :float, null: false)
      add(:phone_last4, :text, null: false)
      add(:assisted_boarding, :boolean, null: false, default: false)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:service_zones, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:code, :text, null: false)
      add(:name, :text, null: false)
      add(:lng, :float, null: false)
      add(:lat, :float, null: false)
      add(:radius_m, :bigint, null: false)
      add(:base_demand, :float, null: false)
      add(:surge, :float, null: false)
      add(:waiting, :bigint, null: false, default: 0)
      add(:event_name, :text)
      add(:event_boost, :float, null: false)
    end

    create unique_index(:service_zones, [:code], name: "service_zones_unique_code_index")

    create table(:telemetry_samples, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:recorded_at, :utc_datetime_usec, null: false)
      add(:lng, :float, null: false)
      add(:lat, :float, null: false)
      add(:speed_kph, :bigint, null: false)
      add(:battery_pct, :bigint, null: false)

      add(
        :cab_id,
        references(:cabs,
          column: :id,
          name: "telemetry_samples_cab_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create index(:telemetry_samples, [:cab_id, :recorded_at],
             name: "telemetry_samples_by_cab_time"
           )

    create table(:trips, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:cabs) do
      modify(
        :trip_id,
        references(:trips, column: :id, name: "cabs_trip_id_fkey", type: :uuid, prefix: "public")
      )
    end

    create constraint(:cabs, :battery_range,
             check: """
               battery_pct BETWEEN 0 AND 100
             """
           )

    alter table(:fleet_alerts) do
      modify(
        :trip_id,
        references(:trips,
          column: :id,
          name: "fleet_alerts_trip_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create index(:fleet_alerts, [:raised_at],
             name: "fleet_alerts_open_by_raised",
             where: "status <> 'resolved'"
           )

    alter table(:trips) do
      add(:code, :text, null: false)
      add(:pickup_name, :text, null: false)
      add(:pickup_lng, :float, null: false)
      add(:pickup_lat, :float, null: false)
      add(:dropoff_name, :text, null: false)
      add(:dropoff_lng, :float, null: false)
      add(:dropoff_lat, :float, null: false)
      add(:ride_polyline, :text, null: false)
      add(:approach_polyline, :text)
      add(:distance_m, :bigint, null: false)
      add(:duration_s, :bigint, null: false)
      add(:surge, :float, null: false)
      add(:fare_cents, :bigint, null: false)
      add(:requested_at, :utc_datetime_usec, null: false)
      add(:assigned_at, :utc_datetime_usec)
      add(:pickup_eta_at, :utc_datetime_usec)
      add(:arrived_at, :utc_datetime_usec)
      add(:picked_up_at, :utc_datetime_usec)
      add(:dropoff_eta_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)
      add(:cancelled_at, :utc_datetime_usec)
      add(:cancel_reason, :text)
      add(:rating, :bigint)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:status, :text, null: false, default: "requested")

      add(
        :rider_id,
        references(:riders,
          column: :id,
          name: "trips_rider_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create unique_index(:trips, [:code], name: "trips_unique_code_index")

    alter table(:trips) do
      add(
        :cab_id,
        references(:cabs, column: :id, name: "trips_cab_id_fkey", type: :uuid, prefix: "public")
      )

      add(
        :zone_id,
        references(:service_zones,
          column: :id,
          name: "trips_zone_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create index(:trips, [:requested_at], name: "trips_by_requested")

    create index(:trips, [:cab_id],
             name: "trips_active_by_cab",
             where: "status IN ('assigned', 'arrived', 'riding')"
           )
  end

  def down do
    drop_if_exists(index(:trips, [:cab_id], name: "trips_active_by_cab"))

    drop_if_exists(index(:trips, [:requested_at], name: "trips_by_requested"))

    drop(constraint(:trips, "trips_zone_id_fkey"))

    drop(constraint(:trips, "trips_cab_id_fkey"))

    drop(constraint(:trips, "trips_rider_id_fkey"))

    alter table(:trips) do
      remove(:zone_id)
      remove(:cab_id)
    end

    drop_if_exists(unique_index(:trips, [:code], name: "trips_unique_code_index"))

    alter table(:trips) do
      remove(:rider_id)
      remove(:status)
      remove(:updated_at)
      remove(:created_at)
      remove(:rating)
      remove(:cancel_reason)
      remove(:cancelled_at)
      remove(:completed_at)
      remove(:dropoff_eta_at)
      remove(:picked_up_at)
      remove(:arrived_at)
      remove(:pickup_eta_at)
      remove(:assigned_at)
      remove(:requested_at)
      remove(:fare_cents)
      remove(:surge)
      remove(:duration_s)
      remove(:distance_m)
      remove(:approach_polyline)
      remove(:ride_polyline)
      remove(:dropoff_lat)
      remove(:dropoff_lng)
      remove(:dropoff_name)
      remove(:pickup_lat)
      remove(:pickup_lng)
      remove(:pickup_name)
      remove(:code)
    end

    drop_if_exists(index(:fleet_alerts, [:raised_at], name: "fleet_alerts_open_by_raised"))

    drop(constraint(:fleet_alerts, "fleet_alerts_trip_id_fkey"))

    drop(constraint(:fleet_alerts, "fleet_alerts_cab_id_fkey"))

    alter table(:fleet_alerts) do
      modify(:trip_id, :uuid)
    end

    drop_if_exists(constraint(:cabs, :battery_range))

    drop(constraint(:cabs, "cabs_trip_id_fkey"))

    drop(constraint(:cabs, "cabs_depot_id_fkey"))

    alter table(:cabs) do
      modify(:trip_id, :uuid)
    end

    drop(table(:trips))

    drop_if_exists(
      index(:telemetry_samples, [:cab_id, :recorded_at], name: "telemetry_samples_by_cab_time")
    )

    drop(constraint(:telemetry_samples, "telemetry_samples_cab_id_fkey"))

    drop(table(:telemetry_samples))

    drop_if_exists(unique_index(:service_zones, [:code], name: "service_zones_unique_code_index"))

    drop(table(:service_zones))

    drop(table(:riders))

    drop_if_exists(index(:pulse_samples, [:recorded_at], name: "pulse_samples_by_time"))

    drop(table(:pulse_samples))

    drop(table(:fleet_alerts))

    drop_if_exists(unique_index(:depots, [:code], name: "depots_unique_code_index"))

    alter table(:depots) do
      remove(:stalls)
      remove(:lat)
      remove(:lng)
      remove(:name)
      remove(:code)
    end

    alter table(:cabs) do
      modify(:depot_id, :uuid)
    end

    drop(table(:depots))

    alter table(:cabs) do
      remove(:trip_id)
    end

    drop_if_exists(unique_index(:cabs, [:vin], name: "cabs_unique_vin_index"))

    drop_if_exists(unique_index(:cabs, [:call_sign], name: "cabs_unique_call_sign_index"))

    drop(table(:cabs))
  end
end
