// ========================================================
// Automatically generated by ash-typescript. DO NOT EDIT.
// ========================================================

import { z } from "zod";

// --- Section 1: Common Types & Filters ---
// Common Ash TypeScript Types
export type SortOrder = "asc" | "desc";

export interface PageInfo {
  hasNextPage: boolean;
  hasPreviousPage: boolean;
  startCursor?: string | null;
  endCursor?: string | null;
}

export interface PaginatedResult<T> {
  results: T[];
  totalCount?: number;
  pageInfo?: PageInfo;
}

export interface UuidFilter {
  eq?: string;
  neq?: string;
  in?: string[];
  is_nil?: boolean;
}

export interface StringFilter {
  eq?: string;
  neq?: string;
  contains?: string;
  starts_with?: string;
  ends_with?: string;
  in?: string[];
  is_nil?: boolean;
}

export interface IntFilter {
  eq?: number;
  neq?: number;
  gt?: number;
  gte?: number;
  lt?: number;
  lte?: number;
  in?: number[];
  is_nil?: boolean;
}

export interface BooleanFilter {
  eq?: boolean;
  neq?: boolean;
  is_nil?: boolean;
}

export interface JsonFilter {
  is_nil?: boolean;
}

// --- Section 2: Resource Types & Action Inputs ---
export interface Ticket {
  id: string;
  title: string;
  description?: string | null;
  status: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";
  priority: number;
  author_id?: string | null;
  author?: Representative | null;
}

export interface OpenTicketInput {
  title: string;
  description?: string | null;
  status: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";
  priority: number;
  author_id?: string | null;
}

export type TicketOpenInput = OpenTicketInput;

export interface ChangeStatusTicketInput {
  id?: string;
  status?: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | null;
}

export type TicketChangeStatusInput = ChangeStatusTicketInput;

export interface UpdateDetailsTicketInput {
  id?: string;
  title?: string | null;
  description?: string | null;
  priority?: number | null;
}

export type TicketUpdateDetailsInput = UpdateDetailsTicketInput;

export interface CloseTicketInput {
  id: string;
}

export type TicketCloseInput = CloseTicketInput;

export interface TicketFilterInput {
  id?: UuidFilter;
  title?: StringFilter;
  description?: StringFilter;
  status?: StringFilter;
  priority?: IntFilter;
  author_id?: UuidFilter;
  and?: TicketFilterInput[];
  or?: TicketFilterInput[];
  not?: TicketFilterInput;
}

export type TicketSortField = "id" | "title" | "description" | "status" | "priority" | "author_id";

export interface TicketSortInput {
  field: TicketSortField;
  order?: SortOrder;
}

export interface TicketInclude {
  author?: boolean | RepresentativeInclude;
}


export interface Representative {
  id: string;
  name: string;
  email: string;
  role: string;
}

export interface CreateRepresentativeInput {
  name: string;
  email: string;
  role: string;
}

export type RepresentativeCreateInput = CreateRepresentativeInput;

export interface RepresentativeFilterInput {
  id?: UuidFilter;
  name?: StringFilter;
  email?: StringFilter;
  role?: StringFilter;
  and?: RepresentativeFilterInput[];
  or?: RepresentativeFilterInput[];
  not?: RepresentativeFilterInput;
}

export type RepresentativeSortField = "id" | "name" | "email" | "role";

export interface RepresentativeSortInput {
  field: RepresentativeSortField;
  order?: SortOrder;
}

export interface RepresentativeInclude {
}


// --- Section 3: Zod Validation Schemas ---
export const TicketSchema = z.object({
  id: z.string().uuid(),
  title: z.string(),
  description: z.string().nullable().optional(),
  status: z.enum(["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"]),
  priority: z.number().int(),
  author_id: z.string().uuid().nullable().optional(),
});

export const OpenTicketInputSchema = z.object({
  title: z.string().min(5).max(100),
  description: z.string().nullable().optional(),
  status: z.enum(["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"]),
  priority: z.number().int().min(1).max(5),
  author_id: z.string().uuid().nullable().optional(),
});

export const TicketOpenInputSchema = OpenTicketInputSchema;

export const ChangeStatusTicketInputSchema = z.object({
  id: z.string().uuid().optional(),
  status: z.enum(["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"]).nullable().optional(),
});

export const TicketChangeStatusInputSchema = ChangeStatusTicketInputSchema;

export const UpdateDetailsTicketInputSchema = z.object({
  id: z.string().uuid().optional(),
  title: z.string().min(5).max(100),
  description: z.string().nullable().optional(),
  priority: z.number().int().min(1).max(5).nullable().optional(),
});

export const TicketUpdateDetailsInputSchema = UpdateDetailsTicketInputSchema;

export const CloseTicketInputSchema = z.object({
  id: z.string().uuid(),
});

export const TicketCloseInputSchema = CloseTicketInputSchema;


export const RepresentativeSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  email: z.string(),
  role: z.string(),
});

export const CreateRepresentativeInputSchema = z.object({
  name: z.string(),
  email: z.string(),
  role: z.string(),
});

export const RepresentativeCreateInputSchema = CreateRepresentativeInputSchema;


// --- Section 4: Isomorphic Client SDK & Transport ---
// Ash Client Runtime & Transport
export interface AshClientConfig {
  baseUrl: string;
  graphqlEndpoint?: string;
  fetch?: typeof fetch;
  headers?: HeadersInit | (() => HeadersInit | Promise<HeadersInit>);
}

export interface AshUserError {
  field?: string;
  message: string;
}

export class AshClientError extends Error {
  public readonly errors: AshUserError[];

  constructor(message: string, errors: AshUserError[] = []) {
    super(message);
    this.name = "AshClientError";
    this.errors = errors;
  }
}

export class AshTransport {
  private readonly defaultEndpoint = "/graphql";

  constructor(private readonly config: AshClientConfig) {}

  public async request<T>(query: string, variables: Record<string, unknown> = {}): Promise<T> {
    const fetchFn = this.config.fetch ?? (typeof fetch !== "undefined" ? fetch : undefined);
    if (!fetchFn) {
      throw new Error("No fetch implementation available. Please pass a custom fetch to AshClientConfig.");
    }

    const base = this.config.baseUrl.replace(/\/$/, "");
    const endpoint = this.config.graphqlEndpoint ?? this.defaultEndpoint;
    const url = `${base}${endpoint.startsWith("/") ? "" : "/"}${endpoint}`;

    let customHeaders: HeadersInit = {};
    if (typeof this.config.headers === "function") {
      customHeaders = await this.config.headers();
    } else if (this.config.headers) {
      customHeaders = this.config.headers;
    }

    const res = await fetchFn(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/json",
        ...customHeaders,
      },
      body: JSON.stringify({ query, variables }),
    });

    if (!res.ok) {
      throw new AshClientError(`HTTP error ${res.status}: ${res.statusText}`);
    }

    const json = (await res.json()) as {
      data?: T;
      errors?: Array<{ message: string; path?: string[] }>;
    };

    if (json.errors && json.errors.length > 0) {
      const userErrors: AshUserError[] = json.errors.map((e) => ({
        field: e.path ? e.path.join(".") : undefined,
        message: e.message,
      }));
      throw new AshClientError(userErrors[0].message || "GraphQL execution error", userErrors);
    }

    if (!json.data) {
      throw new AshClientError("GraphQL returned empty data response");
    }

    return json.data;
  }
}

export function buildTicketSelectionSet(include?: TicketInclude): string {
  let fields = "id title description status priority author_id";
  if (include?.author) {
    const subInclude = typeof include.author === "object" ? include.author : undefined;
    fields += ` author { ${buildRepresentativeSelectionSet(subInclude)} }`;
  }
  return fields;
}

export function buildRepresentativeSelectionSet(include?: RepresentativeInclude): string {
  let fields = "id name email role";
  return fields;
}

export class TicketQueryBuilder {
  private _filter?: TicketFilterInput;
  private _sort: TicketSortInput[] = [];
  private _limit?: number;
  private _offset?: number;
  private _include?: TicketInclude;

  constructor(private readonly transport: AshTransport) {}

  public filter(filter?: TicketFilterInput): this {
    this._filter = filter;
    return this;
  }

  public sort(field: TicketSortField, order: SortOrder = "asc"): this {
    this._sort.push({ field, order });
    return this;
  }

  public limit(limit: number): this {
    this._limit = limit;
    return this;
  }

  public offset(offset: number): this {
    this._offset = offset;
    return this;
  }

  public include(include: TicketInclude): this {
    this._include = { ...this._include, ...include };
    return this;
  }

  public async all(): Promise<Ticket[]> {
    const fields = buildTicketSelectionSet(this._include);
    const query = `query ListTicket($filter: TicketFilterInput, $sort: [TicketSortInput!], $limit: Int, $offset: Int) {
      listTickets(filter: $filter, sort: $sort, limit: $limit, offset: $offset) {
        ${fields}
      }
    }`;

    const data = await this.transport.request<{ listTickets: Ticket[] }>(query, {
      filter: this._filter,
      sort: this._sort.length > 0 ? this._sort : undefined,
      limit: this._limit,
      offset: this._offset,
    });

    return data.listTickets;
  }

  public async first(): Promise<Ticket | null> {
    this._limit = 1;
    const list = await this.all();
    return list[0] ?? null;
  }

  public async page(first: number = 20, after?: string): Promise<PaginatedResult<Ticket>> {
    const fields = buildTicketSelectionSet(this._include);
    const query = `query ConnTicket($filter: TicketFilterInput, $sort: [TicketSortInput!], $first: Int, $after: String) {
      ticketsConnection(filter: $filter, sort: $sort, first: $first, after: $after) {
        edges {
          node {
            ${fields}
          }
          cursor
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
        totalCount
      }
    }`;

    const data = await this.transport.request<{
      ticketsConnection: {
        edges: Array<{ node: Ticket; cursor: string }>;
        pageInfo: PageInfo;
        totalCount?: number;
      };
    }>(query, {
      filter: this._filter,
      sort: this._sort.length > 0 ? this._sort : undefined,
      first,
      after,
    });

    const conn = data.ticketsConnection;
    return {
      results: conn.edges.map((e) => e.node),
      pageInfo: conn.pageInfo,
      totalCount: conn.totalCount,
    };
  }

  public queryOptions() {
    return {
      queryKey: [
        "Ticket",
        "query",
        {
          filter: this._filter,
          sort: this._sort,
          limit: this._limit,
          offset: this._offset,
          include: this._include,
        },
      ],
      queryFn: () => this.all(),
    };
  }

  public pageQueryOptions(first: number = 20, after?: string) {
    return {
      queryKey: [
        "Ticket",
        "page",
        {
          filter: this._filter,
          sort: this._sort,
          first,
          after,
          include: this._include,
        },
      ],
      queryFn: () => this.page(first, after),
    };
  }
}

export class RepresentativeQueryBuilder {
  private _filter?: RepresentativeFilterInput;
  private _sort: RepresentativeSortInput[] = [];
  private _limit?: number;
  private _offset?: number;
  private _include?: RepresentativeInclude;

  constructor(private readonly transport: AshTransport) {}

  public filter(filter?: RepresentativeFilterInput): this {
    this._filter = filter;
    return this;
  }

  public sort(field: RepresentativeSortField, order: SortOrder = "asc"): this {
    this._sort.push({ field, order });
    return this;
  }

  public limit(limit: number): this {
    this._limit = limit;
    return this;
  }

  public offset(offset: number): this {
    this._offset = offset;
    return this;
  }

  public include(include: RepresentativeInclude): this {
    this._include = { ...this._include, ...include };
    return this;
  }

  public async all(): Promise<Representative[]> {
    const fields = buildRepresentativeSelectionSet(this._include);
    const query = `query ListRepresentative($filter: RepresentativeFilterInput, $sort: [RepresentativeSortInput!], $limit: Int, $offset: Int) {
      listRepresentatives(filter: $filter, sort: $sort, limit: $limit, offset: $offset) {
        ${fields}
      }
    }`;

    const data = await this.transport.request<{ listRepresentatives: Representative[] }>(query, {
      filter: this._filter,
      sort: this._sort.length > 0 ? this._sort : undefined,
      limit: this._limit,
      offset: this._offset,
    });

    return data.listRepresentatives;
  }

  public async first(): Promise<Representative | null> {
    this._limit = 1;
    const list = await this.all();
    return list[0] ?? null;
  }

  public async page(first: number = 20, after?: string): Promise<PaginatedResult<Representative>> {
    const fields = buildRepresentativeSelectionSet(this._include);
    const query = `query ConnRepresentative($filter: RepresentativeFilterInput, $sort: [RepresentativeSortInput!], $first: Int, $after: String) {
      representativesConnection(filter: $filter, sort: $sort, first: $first, after: $after) {
        edges {
          node {
            ${fields}
          }
          cursor
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
        totalCount
      }
    }`;

    const data = await this.transport.request<{
      representativesConnection: {
        edges: Array<{ node: Representative; cursor: string }>;
        pageInfo: PageInfo;
        totalCount?: number;
      };
    }>(query, {
      filter: this._filter,
      sort: this._sort.length > 0 ? this._sort : undefined,
      first,
      after,
    });

    const conn = data.representativesConnection;
    return {
      results: conn.edges.map((e) => e.node),
      pageInfo: conn.pageInfo,
      totalCount: conn.totalCount,
    };
  }

  public queryOptions() {
    return {
      queryKey: [
        "Representative",
        "query",
        {
          filter: this._filter,
          sort: this._sort,
          limit: this._limit,
          offset: this._offset,
          include: this._include,
        },
      ],
      queryFn: () => this.all(),
    };
  }

  public pageQueryOptions(first: number = 20, after?: string) {
    return {
      queryKey: [
        "Representative",
        "page",
        {
          filter: this._filter,
          sort: this._sort,
          first,
          after,
          include: this._include,
        },
      ],
      queryFn: () => this.page(first, after),
    };
  }
}

export class TicketClient {
  constructor(private readonly transport: AshTransport) {}

  public query(): TicketQueryBuilder {
    return new TicketQueryBuilder(this.transport);
  }

  public async get(id: string, include?: TicketInclude): Promise<Ticket | null> {
    const fields = buildTicketSelectionSet(include);
    const query = `query GetTicket($id: ID!) {
      getTicket(id: $id) {
        ${fields}
      }
    }`;

    const data = await this.transport.request<{ getTicket: Ticket | null }>(query, { id });
    return data.getTicket;
  }

  public getQueryOptions(id: string, include?: TicketInclude) {
    return {
      queryKey: ["Ticket", "get", id, include],
      queryFn: () => this.get(id, include),
    };
  }

  public async open(input: OpenTicketInput, include?: TicketInclude): Promise<Ticket> {
    const fields = buildTicketSelectionSet(include);
    const query = `mutation MutateTicket($input: OpenTicketInput!) {
      openTicket(input: $input) {
        result {
          ${fields}
        }
        errors {
          field
          message
        }
        success
      }
    }`;

    const data = await this.transport.request<{
      openTicket: {
        result?: Ticket;
        errors: AshUserError[];
        success: boolean;
      };
    }>(query, { input });

    const payload = data.openTicket;
    if (!payload.success || !payload.result) {
      throw new AshClientError(payload.errors[0]?.message || "Mutation failed", payload.errors);
    }

    return payload.result;
  }

  public async changeStatus(id: string, input: ChangeStatusTicketInput, include?: TicketInclude): Promise<Ticket> {
    const fields = buildTicketSelectionSet(include);
    const query = `mutation MutateTicket($input: ChangeStatusTicketInput!) {
      changeStatusTicket(input: $input) {
        result {
          ${fields}
        }
        errors {
          field
          message
        }
        success
      }
    }`;

    const data = await this.transport.request<{
      changeStatusTicket: {
        result?: Ticket;
        errors: AshUserError[];
        success: boolean;
      };
    }>(query, { input: { id, ...input } });

    const payload = data.changeStatusTicket;
    if (!payload.success || !payload.result) {
      throw new AshClientError(payload.errors[0]?.message || "Mutation failed", payload.errors);
    }

    return payload.result;
  }

  public async updateDetails(id: string, input: UpdateDetailsTicketInput, include?: TicketInclude): Promise<Ticket> {
    const fields = buildTicketSelectionSet(include);
    const query = `mutation MutateTicket($input: UpdateDetailsTicketInput!) {
      updateDetailsTicket(input: $input) {
        result {
          ${fields}
        }
        errors {
          field
          message
        }
        success
      }
    }`;

    const data = await this.transport.request<{
      updateDetailsTicket: {
        result?: Ticket;
        errors: AshUserError[];
        success: boolean;
      };
    }>(query, { input: { id, ...input } });

    const payload = data.updateDetailsTicket;
    if (!payload.success || !payload.result) {
      throw new AshClientError(payload.errors[0]?.message || "Mutation failed", payload.errors);
    }

    return payload.result;
  }

  public async close(id: string): Promise<boolean> {
    const query = `mutation MutateTicket($input: CloseTicketInput!) {
      closeTicket(input: $input) {
        errors {
          field
          message
        }
        success
      }
    }`;

    const data = await this.transport.request<{
      closeTicket: {
        errors: AshUserError[];
        success: boolean;
      };
    }>(query, { input: { id } });

    const payload = data.closeTicket;
    if (!payload.success) {
      throw new AshClientError(payload.errors[0]?.message || "Destroy failed", payload.errors);
    }

    return true;
  }
}

export class RepresentativeClient {
  constructor(private readonly transport: AshTransport) {}

  public query(): RepresentativeQueryBuilder {
    return new RepresentativeQueryBuilder(this.transport);
  }

  public async get(id: string, include?: RepresentativeInclude): Promise<Representative | null> {
    const fields = buildRepresentativeSelectionSet(include);
    const query = `query GetRepresentative($id: ID!) {
      getRepresentative(id: $id) {
        ${fields}
      }
    }`;

    const data = await this.transport.request<{ getRepresentative: Representative | null }>(query, { id });
    return data.getRepresentative;
  }

  public getQueryOptions(id: string, include?: RepresentativeInclude) {
    return {
      queryKey: ["Representative", "get", id, include],
      queryFn: () => this.get(id, include),
    };
  }

  public async create(input: CreateRepresentativeInput, include?: RepresentativeInclude): Promise<Representative> {
    const fields = buildRepresentativeSelectionSet(include);
    const query = `mutation MutateRepresentative($input: CreateRepresentativeInput!) {
      createRepresentative(input: $input) {
        result {
          ${fields}
        }
        errors {
          field
          message
        }
        success
      }
    }`;

    const data = await this.transport.request<{
      createRepresentative: {
        result?: Representative;
        errors: AshUserError[];
        success: boolean;
      };
    }>(query, { input });

    const payload = data.createRepresentative;
    if (!payload.success || !payload.result) {
      throw new AshClientError(payload.errors[0]?.message || "Mutation failed", payload.errors);
    }

    return payload.result;
  }
}

export class HelpdeskDomainClient {
  public readonly ticket: TicketClient;
  public readonly representative: RepresentativeClient;

  constructor(transport: AshTransport) {
    this.ticket = new TicketClient(transport);
    this.representative = new RepresentativeClient(transport);
  }
}

export class AshClient {
  public readonly transport: AshTransport;
  public readonly ticket: TicketClient;
  public readonly representative: RepresentativeClient;
  public readonly helpdesk: HelpdeskDomainClient;

  constructor(config: AshClientConfig) {
    this.transport = new AshTransport(config);
    this.ticket = new TicketClient(this.transport);
    this.representative = new RepresentativeClient(this.transport);
    this.helpdesk = new HelpdeskDomainClient(this.transport);
  }
}

export function createAshClient(config: AshClientConfig): AshClient {
  return new AshClient(config);
}

// --- Section 5: React & TanStack Query Helpers ---
export function useTicket(
  client: AshClient,
  id: string,
  include?: TicketInclude,
  options?: Record<string, unknown>
) {
  return {
    ...client.ticket.getQueryOptions(id, include),
    ...options,
  };
}

export function useTicketQuery(
  client: AshClient,
  params?: {
    filter?: TicketFilterInput;
    limit?: number;
    offset?: number;
    include?: TicketInclude;
  },
  options?: Record<string, unknown>
) {
  const builder = client.ticket.query();
  if (params?.filter) builder.filter(params.filter);
  if (params?.limit) builder.limit(params.limit);
  if (params?.offset) builder.offset(params.offset);
  if (params?.include) builder.include(params.include);

  return {
    ...builder.queryOptions(),
    ...options,
  };
}

export function useOpenTicketMutation(
  client: AshClient,
  options?: Record<string, unknown>
) {
  return {
    mutationFn: (variables: { input: OpenTicketInput; include?: TicketInclude }) =>
      client.ticket.open(variables.input, variables.include),
    ...options,
  };
}

export function useChangeStatusTicketMutation(
  client: AshClient,
  options?: Record<string, unknown>
) {
  return {
    mutationFn: (variables: { id: string; input: ChangeStatusTicketInput; include?: TicketInclude }) =>
      client.ticket.changeStatus(variables.id, variables.input, variables.include),
    ...options,
  };
}

export function useUpdateDetailsTicketMutation(
  client: AshClient,
  options?: Record<string, unknown>
) {
  return {
    mutationFn: (variables: { id: string; input: UpdateDetailsTicketInput; include?: TicketInclude }) =>
      client.ticket.updateDetails(variables.id, variables.input, variables.include),
    ...options,
  };
}

export function useCloseTicketMutation(
  client: AshClient,
  options?: Record<string, unknown>
) {
  return {
    mutationFn: (id: string) => client.ticket.close(id),
    ...options,
  };
}

export function useRepresentative(
  client: AshClient,
  id: string,
  include?: RepresentativeInclude,
  options?: Record<string, unknown>
) {
  return {
    ...client.representative.getQueryOptions(id, include),
    ...options,
  };
}

export function useRepresentativeQuery(
  client: AshClient,
  params?: {
    filter?: RepresentativeFilterInput;
    limit?: number;
    offset?: number;
    include?: RepresentativeInclude;
  },
  options?: Record<string, unknown>
) {
  const builder = client.representative.query();
  if (params?.filter) builder.filter(params.filter);
  if (params?.limit) builder.limit(params.limit);
  if (params?.offset) builder.offset(params.offset);
  if (params?.include) builder.include(params.include);

  return {
    ...builder.queryOptions(),
    ...options,
  };
}

export function useCreateRepresentativeMutation(
  client: AshClient,
  options?: Record<string, unknown>
) {
  return {
    mutationFn: (variables: { input: CreateRepresentativeInput; include?: RepresentativeInclude }) =>
      client.representative.create(variables.input, variables.include),
    ...options,
  };
}

