// ========================================================
// Automatically generated by ash-typescript. DO NOT EDIT.
// ========================================================

import { z } from "zod";

// --- Section 1: Common Types & Filters ---
// Common Ash TypeScript Types
export type SortOrder = "asc" | "desc";

/** A keyset page of records, as AshGraphql returns a paginated read. */
export interface PaginatedResult<T> {
  results: T[];
  /** Records matching the query across all pages. */
  count?: number | null;
  startKeyset?: string | null;
  endKeyset?: string | null;
}

/** The operators AshGraphql filters a field by. */
export interface AshFilter<T> {
  isNil?: boolean;
  eq?: T | null;
  notEq?: T | null;
  in?: (T | null)[];
  lessThan?: T;
  greaterThan?: T;
  lessThanOrEqual?: T;
  greaterThanOrEqual?: T;
  isDistinctFrom?: T | null;
  isNotDistinctFrom?: T | null;
}

/** A text field's filter: AshFilter's operators and AshGraphql's text operators. */
export interface AshTextFilter extends AshFilter<string> {
  contains?: string;
  stringStartsWith?: string;
  stringEndsWith?: string;
  like?: string;
  ilike?: string;
}

// --- Section 2: Resource Types & Action Inputs ---
export interface Ticket {
  id: string;
  title: string;
  description?: string | null;
  status: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";
  priority: number;
  estimate?: number | null;
  dueOn?: string | null;
  attachment?: string | null;
  requesterEmail?: string | null;
  authorId?: string | null;
  author?: Representative | null;
}

export interface OpenTicketInput {
  title: string;
  description?: string | null;
  status: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";
  priority: number;
  estimate?: number | null;
  dueOn?: string | null;
  attachment?: string | null;
  requesterEmail?: string | null;
  authorId?: string | null;
}

export type TicketOpenInput = OpenTicketInput;

export interface ChangeStatusTicketInput {
  status?: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | null;
}

export type TicketChangeStatusInput = ChangeStatusTicketInput;

export interface UpdateDetailsTicketInput {
  title?: string | null;
  description?: string | null;
  priority?: number | null;
}

export type TicketUpdateDetailsInput = UpdateDetailsTicketInput;

export interface CloseTicketInput {
}

export type TicketCloseInput = CloseTicketInput;

export interface TicketFilterInput {
  id?: AshFilter<string>;
  title?: AshTextFilter;
  description?: AshTextFilter;
  status?: AshFilter<"OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED">;
  priority?: AshFilter<number>;
  estimate?: AshFilter<number>;
  dueOn?: AshFilter<string>;
  requesterEmail?: AshTextFilter;
  authorId?: AshFilter<string>;
  author?: RepresentativeFilterInput;
  and?: TicketFilterInput[];
  or?: TicketFilterInput[];
  not?: TicketFilterInput[];
}

export type TicketSortField = "id" | "title" | "description" | "status" | "priority" | "estimate" | "dueOn" | "attachment" | "requesterEmail" | "authorId";

export interface TicketSortInput {
  field: TicketSortField;
  order?: SortOrder;
}

export interface TicketInclude {
  author?: boolean | RepresentativeInclude;
}


export interface Representative {
  id: string;
  name: string;
  email: string;
  role: string;
}

export interface CreateRepresentativeInput {
  name: string;
  email: string;
  role: string;
}

export type RepresentativeCreateInput = CreateRepresentativeInput;

export interface RepresentativeFilterInput {
  id?: AshFilter<string>;
  name?: AshTextFilter;
  email?: AshTextFilter;
  role?: AshTextFilter;
  and?: RepresentativeFilterInput[];
  or?: RepresentativeFilterInput[];
  not?: RepresentativeFilterInput[];
}

export type RepresentativeSortField = "id" | "name" | "email" | "role";

export interface RepresentativeSortInput {
  field: RepresentativeSortField;
  order?: SortOrder;
}

export interface RepresentativeInclude {
}


// --- Section 3: Zod Validation Schemas ---
export const TicketSchema = z.object({
  id: z.string().uuid(),
  title: z.string(),
  description: z.string().nullable().optional(),
  status: z.enum(["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"]),
  priority: z.number().int(),
  estimate: z.number().nullable().optional(),
  dueOn: z.string().nullable().optional(),
  attachment: z.string().nullable().optional(),
  requesterEmail: z.string().nullable().optional(),
  authorId: z.string().uuid().nullable().optional(),
});

export const OpenTicketInputSchema = z.object({
  title: z.string().min(5).max(100),
  description: z.string().nullable().optional(),
  status: z.enum(["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"]),
  priority: z.number().int().min(1).max(5),
  estimate: z.number().nullable().optional(),
  dueOn: z.string().nullable().optional(),
  attachment: z.string().nullable().optional(),
  requesterEmail: z.string().nullable().optional(),
  authorId: z.string().uuid().nullable().optional(),
});

export const TicketOpenInputSchema = OpenTicketInputSchema;

export const ChangeStatusTicketInputSchema = z.object({
  status: z.enum(["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"]).nullable().optional(),
});

export const TicketChangeStatusInputSchema = ChangeStatusTicketInputSchema;

export const UpdateDetailsTicketInputSchema = z.object({
  title: z.string().min(5).max(100),
  description: z.string().nullable().optional(),
  priority: z.number().int().min(1).max(5).nullable().optional(),
});

export const TicketUpdateDetailsInputSchema = UpdateDetailsTicketInputSchema;

export const CloseTicketInputSchema = z.object({
});

export const TicketCloseInputSchema = CloseTicketInputSchema;


export const RepresentativeSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  email: z.string(),
  role: z.string(),
});

export const CreateRepresentativeInputSchema = z.object({
  name: z.string(),
  email: z.string(),
  role: z.string(),
});

export const RepresentativeCreateInputSchema = CreateRepresentativeInputSchema;


// --- Section 4: Isomorphic Client SDK & Transport ---
// Ash Client Runtime & Transport
/** The most records a page holds: Ash's default `max_page_size`. */
export const ASH_PAGE_SIZE = 250;

export interface AshClientConfig {
  baseUrl: string;
  graphqlEndpoint?: string;
  fetch?: typeof fetch;
  headers?: HeadersInit | (() => HeadersInit | Promise<HeadersInit>);
}

/** An error a mutation reports, as AshGraphql's `MutationError`, or a GraphQL error. */
export interface AshUserError {
  message: string;
  shortMessage?: string | null;
  /** Ash's error code, e.g. `invalid_attribute`, `required`, `not_found`, `forbidden`. */
  code?: string | null;
  /** The input fields it's about. */
  fields?: string[];
  path?: (string | number)[];
}

export class AshClientError extends Error {
  public readonly errors: AshUserError[];

  constructor(message: string, errors: AshUserError[] = []) {
    super(message);
    this.name = "AshClientError";
    this.errors = errors;
  }
}

export class AshTransport {
  private readonly defaultEndpoint = "/graphql";

  constructor(private readonly config: AshClientConfig) {}

  public async request<T>(query: string, variables: Record<string, unknown> = {}): Promise<T> {
    const fetchFn = this.config.fetch ?? (typeof fetch !== "undefined" ? fetch : undefined);
    if (!fetchFn) {
      throw new Error("No fetch implementation available. Please pass a custom fetch to AshClientConfig.");
    }

    const base = this.config.baseUrl.replace(/\/$/, "");
    const endpoint = this.config.graphqlEndpoint ?? this.defaultEndpoint;
    const url = `${base}${endpoint.startsWith("/") ? "" : "/"}${endpoint}`;

    let customHeaders: HeadersInit = {};
    if (typeof this.config.headers === "function") {
      customHeaders = await this.config.headers();
    } else if (this.config.headers) {
      customHeaders = this.config.headers;
    }

    const res = await fetchFn(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/json",
        ...customHeaders,
      },
      body: JSON.stringify({ query, variables }),
    });

    if (!res.ok) {
      throw new AshClientError(`HTTP error ${res.status}: ${res.statusText}`);
    }

    const json = (await res.json()) as {
      data?: T;
      errors?: Array<{ message: string; path?: (string | number)[] }>;
    };

    if (json.errors && json.errors.length > 0) {
      const userErrors: AshUserError[] = json.errors.map((e) => ({
        message: e.message,
        path: e.path,
      }));
      throw new AshClientError(userErrors[0].message || "GraphQL execution error", userErrors);
    }

    if (!json.data) {
      throw new AshClientError("GraphQL returned empty data response");
    }

    return json.data;
  }
}

export function buildTicketSelectionSet(include?: TicketInclude): string {
  let fields = "id title description status priority estimate dueOn attachment requesterEmail authorId";
  if (include?.author) {
    const subInclude = typeof include.author === "object" ? include.author : undefined;
    fields += ` author { ${buildRepresentativeSelectionSet(subInclude)} }`;
  }
  return fields;
}

export function buildRepresentativeSelectionSet(include?: RepresentativeInclude): string {
  let fields = "id name email role";
  return fields;
}

const TicketSortFieldNames: Record<TicketSortField, string> = { id: "ID", title: "TITLE", description: "DESCRIPTION", status: "STATUS", priority: "PRIORITY", estimate: "ESTIMATE", dueOn: "DUE_ON", attachment: "ATTACHMENT", requesterEmail: "REQUESTER_EMAIL", authorId: "AUTHOR_ID" };

export class TicketQueryBuilder {
  private _filter?: TicketFilterInput;
  private _sort: TicketSortInput[] = [];
  private _limit?: number;
  private _include?: TicketInclude;

  constructor(private readonly transport: AshTransport) {}

  public filter(filter?: TicketFilterInput): this {
    this._filter = filter;
    return this;
  }

  public sort(field: TicketSortField, order: SortOrder = "asc"): this {
    this._sort.push({ field, order });
    return this;
  }

  /** At most this many records, the first in the query's order. */
  public limit(limit: number): this {
    this._limit = limit;
    return this;
  }

  public include(include: TicketInclude): this {
    this._include = { ...this._include, ...include };
    return this;
  }

  /** The sort as the schema takes it: `[{ field: "CALL_SIGN", order: "DESC" }]`. */
  private sortInput() {
    if (this._sort.length === 0) return undefined;
    return this._sort.map(({ field, order }) => ({
      field: TicketSortFieldNames[field],
      order: order === "desc" ? "DESC" : "ASC",
    }));
  }

  private async read(
    paging: { first?: number; after?: string; last?: number; before?: string },
    count: boolean,
  ): Promise<PaginatedResult<Ticket>> {
    const fields = buildTicketSelectionSet(this._include);
    const query = `query ListTicket($filter: TicketFilterInput, $sort: [TicketSortInput], $first: Int, $after: String, $last: Int, $before: String) {
      listTickets(filter: $filter, sort: $sort, first: $first, after: $after, last: $last, before: $before) {
        results {
          ${fields}
        }
        startKeyset
        endKeyset${count ? "\n        count" : ""}
      }
    }`;

    const data = await this.transport.request<{ listTickets: PaginatedResult<Ticket> }>(query, {
      filter: this._filter,
      sort: this.sortInput(),
      ...paging,
    });
    return data.listTickets;
  }

  /**
   * Every matching record, or the first `limit` of them. The server pages every read, as
   * AshGraphql's do, so this reads page after page, each following the last's end keyset.
   */
  public async all(): Promise<Ticket[]> {
    const records: Ticket[] = [];
    let after: string | undefined;
    for (;;) {
      const wanted = this._limit === undefined ? ASH_PAGE_SIZE : Math.min(ASH_PAGE_SIZE, this._limit - records.length);
      if (wanted <= 0) return records;
      const page = await this.read({ first: wanted, after }, false);
      records.push(...page.results);
      if (page.results.length < wanted || !page.endKeyset) return records;
      after = page.endKeyset;
    }
  }

  public async first(): Promise<Ticket | null> {
    const page = await this.read({ first: 1 }, false);
    return page.results[0] ?? null;
  }

  /**
   * A keyset page: `first` records after the `after` keyset, or, given `before`, the
   * `first` records before it. Each page says the keysets at its ends, and how many
   * records match.
   */
  public async page(first: number = 20, after?: string, before?: string): Promise<PaginatedResult<Ticket>> {
    return before !== undefined
      ? this.read({ last: first, before }, true)
      : this.read({ first, after }, true);
  }

  public queryOptions() {
    return {
      queryKey: [
        "Ticket",
        "query",
        {
          filter: this._filter,
          sort: this._sort,
          limit: this._limit,
          include: this._include,
        },
      ],
      queryFn: () => this.all(),
    };
  }

  public pageQueryOptions(first: number = 20, after?: string, before?: string) {
    return {
      queryKey: [
        "Ticket",
        "page",
        {
          filter: this._filter,
          sort: this._sort,
          first,
          after,
          before,
          include: this._include,
        },
      ],
      queryFn: () => this.page(first, after, before),
    };
  }
}

const RepresentativeSortFieldNames: Record<RepresentativeSortField, string> = { id: "ID", name: "NAME", email: "EMAIL", role: "ROLE" };

export class RepresentativeQueryBuilder {
  private _filter?: RepresentativeFilterInput;
  private _sort: RepresentativeSortInput[] = [];
  private _limit?: number;
  private _include?: RepresentativeInclude;

  constructor(private readonly transport: AshTransport) {}

  public filter(filter?: RepresentativeFilterInput): this {
    this._filter = filter;
    return this;
  }

  public sort(field: RepresentativeSortField, order: SortOrder = "asc"): this {
    this._sort.push({ field, order });
    return this;
  }

  /** At most this many records, the first in the query's order. */
  public limit(limit: number): this {
    this._limit = limit;
    return this;
  }

  public include(include: RepresentativeInclude): this {
    this._include = { ...this._include, ...include };
    return this;
  }

  /** The sort as the schema takes it: `[{ field: "CALL_SIGN", order: "DESC" }]`. */
  private sortInput() {
    if (this._sort.length === 0) return undefined;
    return this._sort.map(({ field, order }) => ({
      field: RepresentativeSortFieldNames[field],
      order: order === "desc" ? "DESC" : "ASC",
    }));
  }

  private async read(
    paging: { first?: number; after?: string; last?: number; before?: string },
    count: boolean,
  ): Promise<PaginatedResult<Representative>> {
    const fields = buildRepresentativeSelectionSet(this._include);
    const query = `query ListRepresentative($filter: RepresentativeFilterInput, $sort: [RepresentativeSortInput], $first: Int, $after: String, $last: Int, $before: String) {
      listRepresentatives(filter: $filter, sort: $sort, first: $first, after: $after, last: $last, before: $before) {
        results {
          ${fields}
        }
        startKeyset
        endKeyset${count ? "\n        count" : ""}
      }
    }`;

    const data = await this.transport.request<{ listRepresentatives: PaginatedResult<Representative> }>(query, {
      filter: this._filter,
      sort: this.sortInput(),
      ...paging,
    });
    return data.listRepresentatives;
  }

  /**
   * Every matching record, or the first `limit` of them. The server pages every read, as
   * AshGraphql's do, so this reads page after page, each following the last's end keyset.
   */
  public async all(): Promise<Representative[]> {
    const records: Representative[] = [];
    let after: string | undefined;
    for (;;) {
      const wanted = this._limit === undefined ? ASH_PAGE_SIZE : Math.min(ASH_PAGE_SIZE, this._limit - records.length);
      if (wanted <= 0) return records;
      const page = await this.read({ first: wanted, after }, false);
      records.push(...page.results);
      if (page.results.length < wanted || !page.endKeyset) return records;
      after = page.endKeyset;
    }
  }

  public async first(): Promise<Representative | null> {
    const page = await this.read({ first: 1 }, false);
    return page.results[0] ?? null;
  }

  /**
   * A keyset page: `first` records after the `after` keyset, or, given `before`, the
   * `first` records before it. Each page says the keysets at its ends, and how many
   * records match.
   */
  public async page(first: number = 20, after?: string, before?: string): Promise<PaginatedResult<Representative>> {
    return before !== undefined
      ? this.read({ last: first, before }, true)
      : this.read({ first, after }, true);
  }

  public queryOptions() {
    return {
      queryKey: [
        "Representative",
        "query",
        {
          filter: this._filter,
          sort: this._sort,
          limit: this._limit,
          include: this._include,
        },
      ],
      queryFn: () => this.all(),
    };
  }

  public pageQueryOptions(first: number = 20, after?: string, before?: string) {
    return {
      queryKey: [
        "Representative",
        "page",
        {
          filter: this._filter,
          sort: this._sort,
          first,
          after,
          before,
          include: this._include,
        },
      ],
      queryFn: () => this.page(first, after, before),
    };
  }
}

export class TicketClient {
  constructor(private readonly transport: AshTransport) {}

  public query(): TicketQueryBuilder {
    return new TicketQueryBuilder(this.transport);
  }

  public async get(id: string, include?: TicketInclude): Promise<Ticket | null> {
    const fields = buildTicketSelectionSet(include);
    const query = `query GetTicket($id: ID!) {
      getTicket(id: $id) {
        ${fields}
      }
    }`;

    const data = await this.transport.request<{ getTicket: Ticket | null }>(query, { id });
    return data.getTicket;
  }

  public getQueryOptions(id: string, include?: TicketInclude) {
    return {
      queryKey: ["Ticket", "get", id, include],
      queryFn: () => this.get(id, include),
    };
  }

  public async open(input: OpenTicketInput, include?: TicketInclude): Promise<Ticket> {
    const fields = buildTicketSelectionSet(include);
    const query = `mutation MutateTicket($input: OpenTicketInput!) {
      openTicket(input: $input) {
        result {
          ${fields}
        }
        errors {
          message
          shortMessage
          code
          fields
        }
      }
    }`;

    const data = await this.transport.request<{
      openTicket: {
        result?: Ticket | null;
        errors: AshUserError[];
      };
    }>(query, { input });

    const payload = data.openTicket;
    if (payload.errors.length > 0 || !payload.result) {
      throw new AshClientError(payload.errors[0]?.message || "Mutation failed", payload.errors);
    }

    return payload.result;
  }

  public async changeStatus(id: string, input: ChangeStatusTicketInput = {}, include?: TicketInclude): Promise<Ticket> {
    const fields = buildTicketSelectionSet(include);
    const query = `mutation MutateTicket($id: ID!, $input: ChangeStatusTicketInput) {
      changeStatusTicket(id: $id, input: $input) {
        result {
          ${fields}
        }
        errors {
          message
          shortMessage
          code
          fields
        }
      }
    }`;

    const data = await this.transport.request<{
      changeStatusTicket: {
        result?: Ticket | null;
        errors: AshUserError[];
      };
    }>(query, { id, input });

    const payload = data.changeStatusTicket;
    if (payload.errors.length > 0 || !payload.result) {
      throw new AshClientError(payload.errors[0]?.message || "Mutation failed", payload.errors);
    }

    return payload.result;
  }

  public async updateDetails(id: string, input: UpdateDetailsTicketInput = {}, include?: TicketInclude): Promise<Ticket> {
    const fields = buildTicketSelectionSet(include);
    const query = `mutation MutateTicket($id: ID!, $input: UpdateDetailsTicketInput) {
      updateDetailsTicket(id: $id, input: $input) {
        result {
          ${fields}
        }
        errors {
          message
          shortMessage
          code
          fields
        }
      }
    }`;

    const data = await this.transport.request<{
      updateDetailsTicket: {
        result?: Ticket | null;
        errors: AshUserError[];
      };
    }>(query, { id, input });

    const payload = data.updateDetailsTicket;
    if (payload.errors.length > 0 || !payload.result) {
      throw new AshClientError(payload.errors[0]?.message || "Mutation failed", payload.errors);
    }

    return payload.result;
  }

  public async close(id: string, _input: CloseTicketInput = {}): Promise<boolean> {
    const query = `mutation MutateTicket($id: ID!) {
      closeTicket(id: $id) {
        errors {
          message
          shortMessage
          code
          fields
        }
      }
    }`;

    const data = await this.transport.request<{
      closeTicket: {
        result?: Ticket | null;
        errors: AshUserError[];
      };
    }>(query, { id });

    const payload = data.closeTicket;
    if (payload.errors.length > 0) {
      throw new AshClientError(payload.errors[0]?.message || "Mutation failed", payload.errors);
    }

    return true;
  }
}

export class RepresentativeClient {
  constructor(private readonly transport: AshTransport) {}

  public query(): RepresentativeQueryBuilder {
    return new RepresentativeQueryBuilder(this.transport);
  }

  public async get(id: string, include?: RepresentativeInclude): Promise<Representative | null> {
    const fields = buildRepresentativeSelectionSet(include);
    const query = `query GetRepresentative($id: ID!) {
      getRepresentative(id: $id) {
        ${fields}
      }
    }`;

    const data = await this.transport.request<{ getRepresentative: Representative | null }>(query, { id });
    return data.getRepresentative;
  }

  public getQueryOptions(id: string, include?: RepresentativeInclude) {
    return {
      queryKey: ["Representative", "get", id, include],
      queryFn: () => this.get(id, include),
    };
  }

  public async create(input: CreateRepresentativeInput, include?: RepresentativeInclude): Promise<Representative> {
    const fields = buildRepresentativeSelectionSet(include);
    const query = `mutation MutateRepresentative($input: CreateRepresentativeInput!) {
      createRepresentative(input: $input) {
        result {
          ${fields}
        }
        errors {
          message
          shortMessage
          code
          fields
        }
      }
    }`;

    const data = await this.transport.request<{
      createRepresentative: {
        result?: Representative | null;
        errors: AshUserError[];
      };
    }>(query, { input });

    const payload = data.createRepresentative;
    if (payload.errors.length > 0 || !payload.result) {
      throw new AshClientError(payload.errors[0]?.message || "Mutation failed", payload.errors);
    }

    return payload.result;
  }
}

export class HelpdeskDomainClient {
  public readonly ticket: TicketClient;
  public readonly representative: RepresentativeClient;

  constructor(transport: AshTransport) {
    this.ticket = new TicketClient(transport);
    this.representative = new RepresentativeClient(transport);
  }
}

export class AshClient {
  public readonly transport: AshTransport;
  public readonly ticket: TicketClient;
  public readonly representative: RepresentativeClient;
  public readonly helpdesk: HelpdeskDomainClient;

  constructor(config: AshClientConfig) {
    this.transport = new AshTransport(config);
    this.ticket = new TicketClient(this.transport);
    this.representative = new RepresentativeClient(this.transport);
    this.helpdesk = new HelpdeskDomainClient(this.transport);
  }
}

export function createAshClient(config: AshClientConfig): AshClient {
  return new AshClient(config);
}

// --- Section 5: React & TanStack Query Helpers ---
export function useTicket(
  client: AshClient,
  id: string,
  include?: TicketInclude,
  options?: Record<string, unknown>
) {
  return {
    ...client.ticket.getQueryOptions(id, include),
    ...options,
  };
}

export function useTicketQuery(
  client: AshClient,
  params?: {
    filter?: TicketFilterInput;
    limit?: number;
    include?: TicketInclude;
  },
  options?: Record<string, unknown>
) {
  const builder = client.ticket.query();
  if (params?.filter) builder.filter(params.filter);
  if (params?.limit) builder.limit(params.limit);
  if (params?.include) builder.include(params.include);

  return {
    ...builder.queryOptions(),
    ...options,
  };
}

export function useOpenTicketMutation(
  client: AshClient,
  options?: Record<string, unknown>
) {
  return {
    mutationFn: (variables: { input: OpenTicketInput; include?: TicketInclude }) =>
      client.ticket.open(variables.input, variables.include),
    ...options,
  };
}

export function useChangeStatusTicketMutation(
  client: AshClient,
  options?: Record<string, unknown>
) {
  return {
    mutationFn: (variables: { id: string; input: ChangeStatusTicketInput; include?: TicketInclude }) =>
      client.ticket.changeStatus(variables.id, variables.input, variables.include),
    ...options,
  };
}

export function useUpdateDetailsTicketMutation(
  client: AshClient,
  options?: Record<string, unknown>
) {
  return {
    mutationFn: (variables: { id: string; input: UpdateDetailsTicketInput; include?: TicketInclude }) =>
      client.ticket.updateDetails(variables.id, variables.input, variables.include),
    ...options,
  };
}

export function useCloseTicketMutation(
  client: AshClient,
  options?: Record<string, unknown>
) {
  return {
    mutationFn: (id: string) => client.ticket.close(id),
    ...options,
  };
}

export function useRepresentative(
  client: AshClient,
  id: string,
  include?: RepresentativeInclude,
  options?: Record<string, unknown>
) {
  return {
    ...client.representative.getQueryOptions(id, include),
    ...options,
  };
}

export function useRepresentativeQuery(
  client: AshClient,
  params?: {
    filter?: RepresentativeFilterInput;
    limit?: number;
    include?: RepresentativeInclude;
  },
  options?: Record<string, unknown>
) {
  const builder = client.representative.query();
  if (params?.filter) builder.filter(params.filter);
  if (params?.limit) builder.limit(params.limit);
  if (params?.include) builder.include(params.include);

  return {
    ...builder.queryOptions(),
    ...options,
  };
}

export function useCreateRepresentativeMutation(
  client: AshClient,
  options?: Record<string, unknown>
) {
  return {
    mutationFn: (variables: { input: CreateRepresentativeInput; include?: RepresentativeInclude }) =>
      client.representative.create(variables.input, variables.include),
    ...options,
  };
}

