{application,markdown_formatter,
             [{modules,['Elixir.Collectable.MarkdownFormatter.Renderer.Q',
                        'Elixir.Enumerable.MarkdownFormatter.Renderer.Q',
                        'Elixir.Inspect.MarkdownFormatter.Renderer.Q',
                        'Elixir.MarkdownFormatter',
                        'Elixir.MarkdownFormatter.Renderer',
                        'Elixir.MarkdownFormatter.Renderer.Q',
                        'Elixir.MarkdownFormatter.Renderer.RenderState',
                        'Elixir.String.Chars.MarkdownFormatter.Renderer.Q']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,earmark_parser]},
              {description,"A mix format plugin for markdown files"},
              {registered,[]},
              {vsn,"0.6.0"}]}.
