//! # Pattern 1: Additive Token-Forwarding (`extend <macro_path>! { ... }`)
//!
//! ## Overview & Use Cases
//!
//! Pattern 1 is the cleanest, lowest-overhead way for **any third-party crate**
//! to extend `ash-rust` resources without modifying `ash-core` or `ash-macros`.
//!
//! ### When to use Pattern 1:
//! - **Additive / Companion Features**: Generating companion traits, event listeners,
//!   search indexers, audit log tables, or GraphQL/OpenAPI schema metadata.
//! - **Zero Coupling**: The author of `my-extension` can define a declarative macro DSL,
//!   and users invoke it directly inside `resource!`. `ash-macros` simply forwards the tokens:
//!   `my_extension::macro!(ResourceName, { <user's tokens> });`
//!
//! ### How this differs from Pattern 2 (Transformer Decorator):
//! - Pattern 1 does **not** rewrite the core resource AST (it does not inject fields into `attributes`
//!   or alter `actions`).
//! - If an extension *needs* to inject attributes or synthesize actions, use Pattern 2 (`#[state_machine] resource!`).
//! - If an extension only needs to generate companion code or register metadata, Pattern 1 is optimal.

use ash_core::{Context, resource};
use ash_memory::Memory;
use uuid::Uuid;

/// Mock 3rd-party extension crate: `ash-audit`
/// Generates an `Auditable` trait implementation for the target resource.
macro_rules! audit_trail {
    ($resource:ident, { track: [$($field:ident),* $(,)?]; }) => {
        pub trait Auditable {
            fn tracked_fields() -> &'static [&'static str];
        }

        impl Auditable for $resource {
            fn tracked_fields() -> &'static [&'static str] {
                &[$(stringify!($field)),*]
            }
        }
    };
}

/// Mock 3rd-party extension crate: `ash-search`
/// Generates a `Searchable` trait implementation specifying the index name.
macro_rules! searchable {
    ($resource:ident, { index: $idx:literal; }) => {
        pub trait Searchable {
            fn search_index() -> &'static str;
        }

        impl Searchable for $resource {
            fn search_index() -> &'static str {
                $idx
            }
        }
    };
}

// Define resource using Pattern 1 `extend` blocks
resource! {
    resource Product;
    table "products";

    attributes {
        id: Uuid [pk],
        title: String,
        price: i64,
    }

    actions {
        create create {
            primary;
            accept [title, price];
        }

        read read {
            primary;
        }
    }

    // Pattern 1 Extension A: audit tracking
    extend audit_trail! {
        track: [price];
    }

    // Pattern 1 Extension B: search engine indexing
    extend searchable! {
        index: "products_v1";
    }
}

#[tokio::test]
async fn test_pattern1_extend_companion_traits_and_crud() {
    // 1. Verify companion traits generated by `extend audit_trail!`
    assert_eq!(Product::tracked_fields(), &["price"]);

    // 2. Verify companion traits generated by `extend searchable!`
    assert_eq!(Product::search_index(), "products_v1");

    // 3. Verify normal resource functionality remains 100% operational
    let ctx = Context::new(Memory::new());
    let product = Product::create(&ctx)
        .title("Mechanical Keyboard")
        .price(150)
        .await
        .expect("create product");

    assert_eq!(product.title, "Mechanical Keyboard");
    assert_eq!(product.price, 150);
}
